#pragma once
#include <RaylibWrapper/export.h>
#include <RaylibWrapper/RaylibWrapper.hpp>

#if defined(RAYLIBWRAPPER_SHARED_EXPORT)
#  define RAYLIBWRAPPER_API RAYLIBWRAPPER_SHARED_EXPORT
#elif defined(RAYLIBWRAPPER_STATIC_EXPORT)
#  define RAYLIBWRAPPER_API RAYLIBWRAPPER_STATIC_EXPORT
#else
#  define RAYLIBWRAPPER_API
#endif

#ifdef __cplusplus
// bring rlw types (Vector2, Color, etc.) into global scope for these C wrappers
using namespace rlw;
extern "C" {
#endif

RAYLIBWRAPPER_API void rlw_InitWindow(int width, int height, const char *title);
RAYLIBWRAPPER_API void rlw_CloseWindow(void);
RAYLIBWRAPPER_API bool rlw_WindowShouldClose(void);
RAYLIBWRAPPER_API bool rlw_IsWindowReady(void);
RAYLIBWRAPPER_API bool rlw_IsWindowFullscreen(void);
RAYLIBWRAPPER_API bool rlw_IsWindowHidden(void);
RAYLIBWRAPPER_API bool rlw_IsWindowMinimized(void);
RAYLIBWRAPPER_API bool rlw_IsWindowMaximized(void);
RAYLIBWRAPPER_API bool rlw_IsWindowFocused(void);
RAYLIBWRAPPER_API bool rlw_IsWindowResized(void);
RAYLIBWRAPPER_API bool rlw_IsWindowState(unsigned int flag);
RAYLIBWRAPPER_API void rlw_SetWindowState(unsigned int flags);
RAYLIBWRAPPER_API void rlw_ClearWindowState(unsigned int flags);
RAYLIBWRAPPER_API void rlw_ToggleFullscreen(void);
RAYLIBWRAPPER_API void rlw_ToggleBorderlessWindowed(void);
RAYLIBWRAPPER_API void rlw_MaximizeWindow(void);
RAYLIBWRAPPER_API void rlw_MinimizeWindow(void);
RAYLIBWRAPPER_API void rlw_RestoreWindow(void);
RAYLIBWRAPPER_API void rlw_SetWindowIcon(Image image);
RAYLIBWRAPPER_API void rlw_SetWindowIcons(Image *images, int count);
RAYLIBWRAPPER_API void rlw_SetWindowTitle(const char *title);
RAYLIBWRAPPER_API void rlw_SetWindowPosition(int x, int y);
RAYLIBWRAPPER_API void rlw_SetWindowMonitor(int monitor);
RAYLIBWRAPPER_API void rlw_SetWindowMinSize(int width, int height);
RAYLIBWRAPPER_API void rlw_SetWindowMaxSize(int width, int height);
RAYLIBWRAPPER_API void rlw_SetWindowSize(int width, int height);
RAYLIBWRAPPER_API void rlw_SetWindowOpacity(float opacity);
RAYLIBWRAPPER_API void rlw_SetWindowFocused(void);
RAYLIBWRAPPER_API int rlw_GetScreenWidth(void);
RAYLIBWRAPPER_API int rlw_GetScreenHeight(void);
RAYLIBWRAPPER_API int rlw_GetRenderWidth(void);
RAYLIBWRAPPER_API int rlw_GetRenderHeight(void);
RAYLIBWRAPPER_API int rlw_GetMonitorCount(void);
RAYLIBWRAPPER_API int rlw_GetCurrentMonitor(void);
RAYLIBWRAPPER_API Vector2 rlw_GetMonitorPosition(int monitor);
RAYLIBWRAPPER_API int rlw_GetMonitorWidth(int monitor);
RAYLIBWRAPPER_API int rlw_GetMonitorHeight(int monitor);
RAYLIBWRAPPER_API int rlw_GetMonitorPhysicalWidth(int monitor);
RAYLIBWRAPPER_API int rlw_GetMonitorPhysicalHeight(int monitor);
RAYLIBWRAPPER_API int rlw_GetMonitorRefreshRate(int monitor);
RAYLIBWRAPPER_API Vector2 rlw_GetWindowPosition(void);
RAYLIBWRAPPER_API Vector2 rlw_GetWindowScaleDPI(void);
RAYLIBWRAPPER_API void rlw_SetClipboardText(const char *text);
RAYLIBWRAPPER_API void rlw_EnableEventWaiting(void);
RAYLIBWRAPPER_API void rlw_DisableEventWaiting(void);
RAYLIBWRAPPER_API void rlw_ShowCursor(void);
RAYLIBWRAPPER_API void rlw_HideCursor(void);
RAYLIBWRAPPER_API bool rlw_IsCursorHidden(void);
RAYLIBWRAPPER_API void rlw_EnableCursor(void);
RAYLIBWRAPPER_API void rlw_DisableCursor(void);
RAYLIBWRAPPER_API bool rlw_IsCursorOnScreen(void);
RAYLIBWRAPPER_API void rlw_ClearBackground(Color color);
RAYLIBWRAPPER_API void rlw_BeginDrawing(void);
RAYLIBWRAPPER_API void rlw_EndDrawing(void);
RAYLIBWRAPPER_API void rlw_BeginMode2D(Camera2D camera);
RAYLIBWRAPPER_API void rlw_EndMode2D(void);
RAYLIBWRAPPER_API void rlw_BeginMode3D(Camera3D camera);
RAYLIBWRAPPER_API void rlw_EndMode3D(void);
RAYLIBWRAPPER_API void rlw_BeginTextureMode(RenderTexture2D target);
RAYLIBWRAPPER_API void rlw_EndTextureMode(void);
RAYLIBWRAPPER_API void rlw_BeginShaderMode(Shader shader);
RAYLIBWRAPPER_API void rlw_EndShaderMode(void);
RAYLIBWRAPPER_API void rlw_BeginBlendMode(int mode);
RAYLIBWRAPPER_API void rlw_EndBlendMode(void);
RAYLIBWRAPPER_API void rlw_BeginScissorMode(int x, int y, int width, int height);
RAYLIBWRAPPER_API void rlw_EndScissorMode(void);
RAYLIBWRAPPER_API void rlw_BeginVrStereoMode(VrStereoConfig config);
RAYLIBWRAPPER_API void rlw_EndVrStereoMode(void);
RAYLIBWRAPPER_API VrStereoConfig rlw_LoadVrStereoConfig(VrDeviceInfo device);
RAYLIBWRAPPER_API void rlw_UnloadVrStereoConfig(VrStereoConfig config);
RAYLIBWRAPPER_API Shader rlw_LoadShader(const char *vsFileName, const char *fsFileName);
RAYLIBWRAPPER_API Shader rlw_LoadShaderFromMemory(const char *vsCode, const char *fsCode);
RAYLIBWRAPPER_API bool rlw_IsShaderValid(Shader shader);
RAYLIBWRAPPER_API int rlw_GetShaderLocation(Shader shader, const char *uniformName);
RAYLIBWRAPPER_API int rlw_GetShaderLocationAttrib(Shader shader, const char *attribName);
RAYLIBWRAPPER_API void rlw_SetShaderValue(Shader shader, int locIndex, const void *value, int uniformType);
RAYLIBWRAPPER_API void rlw_SetShaderValueV(Shader shader, int locIndex, const void *value, int uniformType, int count);
RAYLIBWRAPPER_API void rlw_SetShaderValueMatrix(Shader shader, int locIndex, Matrix mat);
RAYLIBWRAPPER_API void rlw_SetShaderValueTexture(Shader shader, int locIndex, Texture2D texture);
RAYLIBWRAPPER_API void rlw_UnloadShader(Shader shader);
RAYLIBWRAPPER_API Ray rlw_GetScreenToWorldRay(Vector2 mousePosition, Camera camera);
RAYLIBWRAPPER_API Matrix rlw_GetCameraMatrix(Camera camera);
RAYLIBWRAPPER_API Matrix rlw_GetCameraMatrix2D(Camera2D camera);
RAYLIBWRAPPER_API Vector2 rlw_GetWorldToScreen(Vector3 position, Camera camera);
RAYLIBWRAPPER_API Vector2 rlw_GetScreenToWorld2D(Vector2 position, Camera2D camera);
RAYLIBWRAPPER_API Vector2 rlw_GetWorldToScreenEx(Vector3 position, Camera camera, int width, int height);
RAYLIBWRAPPER_API Vector2 rlw_GetWorldToScreen2D(Vector2 position, Camera2D camera);
RAYLIBWRAPPER_API void rlw_SetTargetFPS(int fps);
RAYLIBWRAPPER_API float rlw_GetFrameTime(void);
RAYLIBWRAPPER_API double rlw_GetTime(void);
RAYLIBWRAPPER_API int rlw_GetFPS(void);
RAYLIBWRAPPER_API void rlw_SwapScreenBuffer(void);
RAYLIBWRAPPER_API void rlw_PollInputEvents(void);
RAYLIBWRAPPER_API void rlw_WaitTime(double seconds);
RAYLIBWRAPPER_API void rlw_SetRandomSeed(unsigned int seed);
RAYLIBWRAPPER_API int rlw_GetRandomValue(int min, int max);
RAYLIBWRAPPER_API void rlw_UnloadRandomSequence(int *sequence);
RAYLIBWRAPPER_API void rlw_TakeScreenshot(const char *fileName);
RAYLIBWRAPPER_API void rlw_SetConfigFlags(unsigned int flags);
RAYLIBWRAPPER_API void rlw_OpenURL(const char *url);
RAYLIBWRAPPER_API void rlw_TraceLog(int logLevel, const char *text, ...);
RAYLIBWRAPPER_API void rlw_SetTraceLogLevel(int logLevel);
RAYLIBWRAPPER_API void rlw_MemFree(void *ptr);
RAYLIBWRAPPER_API void rlw_SetTraceLogCallback(TraceLogCallback callback);
RAYLIBWRAPPER_API void rlw_SetLoadFileDataCallback(LoadFileDataCallback callback);
RAYLIBWRAPPER_API void rlw_SetSaveFileDataCallback(SaveFileDataCallback callback);
RAYLIBWRAPPER_API void rlw_SetLoadFileTextCallback(LoadFileTextCallback callback);
RAYLIBWRAPPER_API void rlw_SetSaveFileTextCallback(SaveFileTextCallback callback);
RAYLIBWRAPPER_API void rlw_UnloadFileData(unsigned char *data);
RAYLIBWRAPPER_API bool rlw_SaveFileData(const char *fileName, void *data, int dataSize);
RAYLIBWRAPPER_API bool rlw_ExportDataAsCode(const unsigned char *data, int dataSize, const char *fileName);
RAYLIBWRAPPER_API void rlw_UnloadFileText(char *text);
RAYLIBWRAPPER_API bool rlw_SaveFileText(const char *fileName, char *text);
RAYLIBWRAPPER_API bool rlw_FileExists(const char *fileName);
RAYLIBWRAPPER_API bool rlw_DirectoryExists(const char *dirPath);
RAYLIBWRAPPER_API bool rlw_IsFileExtension(const char *fileName, const char *ext);
RAYLIBWRAPPER_API int rlw_GetFileLength(const char *fileName);
RAYLIBWRAPPER_API bool rlw_ChangeDirectory(const char *dir);
RAYLIBWRAPPER_API bool rlw_IsPathFile(const char *path);
RAYLIBWRAPPER_API FilePathList rlw_LoadDirectoryFiles(const char *dirPath);
RAYLIBWRAPPER_API FilePathList rlw_LoadDirectoryFilesEx(const char *basePath, const char *filter, bool scanSubdirs);
RAYLIBWRAPPER_API void rlw_UnloadDirectoryFiles(FilePathList files);
RAYLIBWRAPPER_API bool rlw_IsFileDropped(void);
RAYLIBWRAPPER_API FilePathList rlw_LoadDroppedFiles(void);
RAYLIBWRAPPER_API void rlw_UnloadDroppedFiles(FilePathList files);
RAYLIBWRAPPER_API long rlw_GetFileModTime(const char *fileName);
RAYLIBWRAPPER_API AutomationEventList rlw_LoadAutomationEventList(const char *fileName);
RAYLIBWRAPPER_API void rlw_UnloadAutomationEventList(AutomationEventList list);
RAYLIBWRAPPER_API bool rlw_ExportAutomationEventList(AutomationEventList list, const char *fileName);
RAYLIBWRAPPER_API void rlw_SetAutomationEventList(AutomationEventList *list);
RAYLIBWRAPPER_API void rlw_SetAutomationEventBaseFrame(int frame);
RAYLIBWRAPPER_API void rlw_StartAutomationEventRecording(void);
RAYLIBWRAPPER_API void rlw_StopAutomationEventRecording(void);
RAYLIBWRAPPER_API void rlw_PlayAutomationEvent(AutomationEvent event);
RAYLIBWRAPPER_API bool rlw_IsKeyPressed(int key);
RAYLIBWRAPPER_API bool rlw_IsKeyPressedRepeat(int key);
RAYLIBWRAPPER_API bool rlw_IsKeyDown(int key);
RAYLIBWRAPPER_API bool rlw_IsKeyReleased(int key);
RAYLIBWRAPPER_API bool rlw_IsKeyUp(int key);
RAYLIBWRAPPER_API int rlw_GetKeyPressed(void);
RAYLIBWRAPPER_API int rlw_GetCharPressed(void);
RAYLIBWRAPPER_API void rlw_SetExitKey(int key);
RAYLIBWRAPPER_API bool rlw_IsGamepadAvailable(int gamepad);
RAYLIBWRAPPER_API bool rlw_IsGamepadButtonPressed(int gamepad, int button);
RAYLIBWRAPPER_API bool rlw_IsGamepadButtonDown(int gamepad, int button);
RAYLIBWRAPPER_API bool rlw_IsGamepadButtonReleased(int gamepad, int button);
RAYLIBWRAPPER_API bool rlw_IsGamepadButtonUp(int gamepad, int button);
RAYLIBWRAPPER_API int rlw_GetGamepadButtonPressed(void);
RAYLIBWRAPPER_API int rlw_GetGamepadAxisCount(int gamepad);
RAYLIBWRAPPER_API float rlw_GetGamepadAxisMovement(int gamepad, int axis);
RAYLIBWRAPPER_API int rlw_SetGamepadMappings(const char *mappings);
RAYLIBWRAPPER_API bool rlw_IsMouseButtonPressed(int button);
RAYLIBWRAPPER_API bool rlw_IsMouseButtonDown(int button);
RAYLIBWRAPPER_API bool rlw_IsMouseButtonReleased(int button);
RAYLIBWRAPPER_API bool rlw_IsMouseButtonUp(int button);
RAYLIBWRAPPER_API int rlw_GetMouseX(void);
RAYLIBWRAPPER_API int rlw_GetMouseY(void);
RAYLIBWRAPPER_API Vector2 rlw_GetMousePosition(void);
RAYLIBWRAPPER_API Vector2 rlw_GetMouseDelta(void);
RAYLIBWRAPPER_API void rlw_SetMousePosition(int x, int y);
RAYLIBWRAPPER_API void rlw_SetMouseOffset(int offsetX, int offsetY);
RAYLIBWRAPPER_API void rlw_SetMouseScale(float scaleX, float scaleY);
RAYLIBWRAPPER_API float rlw_GetMouseWheelMove(void);
RAYLIBWRAPPER_API Vector2 rlw_GetMouseWheelMoveV(void);
RAYLIBWRAPPER_API void rlw_SetMouseCursor(int cursor);
RAYLIBWRAPPER_API int rlw_GetTouchX(void);
RAYLIBWRAPPER_API int rlw_GetTouchY(void);
RAYLIBWRAPPER_API Vector2 rlw_GetTouchPosition(int index);
RAYLIBWRAPPER_API int rlw_GetTouchPointId(int index);
RAYLIBWRAPPER_API int rlw_GetTouchPointCount(void);
RAYLIBWRAPPER_API void rlw_SetGesturesEnabled(unsigned int flags);
RAYLIBWRAPPER_API bool rlw_IsGestureDetected(unsigned int gesture);
RAYLIBWRAPPER_API int rlw_GetGestureDetected(void);
RAYLIBWRAPPER_API float rlw_GetGestureHoldDuration(void);
RAYLIBWRAPPER_API Vector2 rlw_GetGestureDragVector(void);
RAYLIBWRAPPER_API float rlw_GetGestureDragAngle(void);
RAYLIBWRAPPER_API Vector2 rlw_GetGesturePinchVector(void);
RAYLIBWRAPPER_API float rlw_GetGesturePinchAngle(void);
RAYLIBWRAPPER_API void rlw_UpdateCamera(Camera *camera, int mode);
RAYLIBWRAPPER_API void rlw_UpdateCameraPro(Camera *camera, Vector3 movement, Vector3 rotation, float zoom);
RAYLIBWRAPPER_API void rlw_SetShapesTexture(Texture2D texture, Rectangle source);
RAYLIBWRAPPER_API void rlw_DrawPixel(int posX, int posY, Color color);
RAYLIBWRAPPER_API void rlw_DrawPixelV(Vector2 position, Color color);
RAYLIBWRAPPER_API void rlw_DrawLine(int startPosX, int startPosY, int endPosX, int endPosY, Color color);
RAYLIBWRAPPER_API void rlw_DrawLineV(Vector2 startPos, Vector2 endPos, Color color);
RAYLIBWRAPPER_API void rlw_DrawLineEx(Vector2 startPos, Vector2 endPos, float thick, Color color);
RAYLIBWRAPPER_API void rlw_DrawLineStrip(Vector2 *points, int pointCount, Color color);
RAYLIBWRAPPER_API void rlw_DrawLineBezier(Vector2 startPos, Vector2 endPos, float thick, Color color);
RAYLIBWRAPPER_API void rlw_DrawCircle(int centerX, int centerY, float radius, Color color);
RAYLIBWRAPPER_API void rlw_DrawCircleSector(Vector2 center, float radius, float startAngle, float endAngle, int segments, Color color);
RAYLIBWRAPPER_API void rlw_DrawCircleSectorLines(Vector2 center, float radius, float startAngle, float endAngle, int segments, Color color);
RAYLIBWRAPPER_API void rlw_DrawCircleGradient(int centerX, int centerY, float radius, Color color1, Color color2);
RAYLIBWRAPPER_API void rlw_DrawCircleV(Vector2 center, float radius, Color color);
RAYLIBWRAPPER_API void rlw_DrawCircleLines(int centerX, int centerY, float radius, Color color);
RAYLIBWRAPPER_API void rlw_DrawCircleLinesV(Vector2 center, float radius, Color color);
RAYLIBWRAPPER_API void rlw_DrawEllipse(int centerX, int centerY, float radiusH, float radiusV, Color color);
RAYLIBWRAPPER_API void rlw_DrawEllipseLines(int centerX, int centerY, float radiusH, float radiusV, Color color);
RAYLIBWRAPPER_API void rlw_DrawRing(Vector2 center, float innerRadius, float outerRadius, float startAngle, float endAngle, int segments, Color color);
RAYLIBWRAPPER_API void rlw_DrawRingLines(Vector2 center, float innerRadius, float outerRadius, float startAngle, float endAngle, int segments, Color color);
RAYLIBWRAPPER_API void rlw_DrawRectangle(int posX, int posY, int width, int height, Color color);
RAYLIBWRAPPER_API void rlw_DrawRectangleV(Vector2 position, Vector2 size, Color color);
RAYLIBWRAPPER_API void rlw_DrawRectangleRec(Rectangle rec, Color color);
RAYLIBWRAPPER_API void rlw_DrawRectanglePro(Rectangle rec, Vector2 origin, float rotation, Color color);
RAYLIBWRAPPER_API void rlw_DrawRectangleGradientV(int posX, int posY, int width, int height, Color color1, Color color2);
RAYLIBWRAPPER_API void rlw_DrawRectangleGradientH(int posX, int posY, int width, int height, Color color1, Color color2);
RAYLIBWRAPPER_API void rlw_DrawRectangleGradientEx(Rectangle rec, Color col1, Color col2, Color col3, Color col4);
RAYLIBWRAPPER_API void rlw_DrawRectangleLines(int posX, int posY, int width, int height, Color color);
RAYLIBWRAPPER_API void rlw_DrawRectangleLinesEx(Rectangle rec, float lineThick, Color color);
RAYLIBWRAPPER_API void rlw_DrawRectangleRounded(Rectangle rec, float roundness, int segments, Color color);
RAYLIBWRAPPER_API void rlw_DrawRectangleRoundedLines(Rectangle rec, float roundness, int segments, Color color);
RAYLIBWRAPPER_API void rlw_DrawTriangle(Vector2 v1, Vector2 v2, Vector2 v3, Color color);
RAYLIBWRAPPER_API void rlw_DrawTriangleLines(Vector2 v1, Vector2 v2, Vector2 v3, Color color);
RAYLIBWRAPPER_API void rlw_DrawTriangleFan(Vector2 *points, int pointCount, Color color);
RAYLIBWRAPPER_API void rlw_DrawTriangleStrip(Vector2 *points, int pointCount, Color color);
RAYLIBWRAPPER_API void rlw_DrawPoly(Vector2 center, int sides, float radius, float rotation, Color color);
RAYLIBWRAPPER_API void rlw_DrawPolyLines(Vector2 center, int sides, float radius, float rotation, Color color);
RAYLIBWRAPPER_API void rlw_DrawPolyLinesEx(Vector2 center, int sides, float radius, float rotation, float lineThick, Color color);
RAYLIBWRAPPER_API void rlw_DrawSplineLinear(Vector2 *points, int pointCount, float thick, Color color);
RAYLIBWRAPPER_API void rlw_DrawSplineBasis(Vector2 *points, int pointCount, float thick, Color color);
RAYLIBWRAPPER_API void rlw_DrawSplineCatmullRom(Vector2 *points, int pointCount, float thick, Color color);
RAYLIBWRAPPER_API void rlw_DrawSplineBezierQuadratic(Vector2 *points, int pointCount, float thick, Color color);
RAYLIBWRAPPER_API void rlw_DrawSplineBezierCubic(Vector2 *points, int pointCount, float thick, Color color);
RAYLIBWRAPPER_API void rlw_DrawSplineSegmentLinear(Vector2 p1, Vector2 p2, float thick, Color color);
RAYLIBWRAPPER_API void rlw_DrawSplineSegmentBasis(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, float thick, Color color);
RAYLIBWRAPPER_API void rlw_DrawSplineSegmentCatmullRom(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, float thick, Color color);
RAYLIBWRAPPER_API void rlw_DrawSplineSegmentBezierQuadratic(Vector2 p1, Vector2 c2, Vector2 p3, float thick, Color color);
RAYLIBWRAPPER_API void rlw_DrawSplineSegmentBezierCubic(Vector2 p1, Vector2 c2, Vector2 c3, Vector2 p4, float thick, Color color);
RAYLIBWRAPPER_API Vector2 rlw_GetSplinePointLinear(Vector2 startPos, Vector2 endPos, float t);
RAYLIBWRAPPER_API Vector2 rlw_GetSplinePointBasis(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, float t);
RAYLIBWRAPPER_API Vector2 rlw_GetSplinePointCatmullRom(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, float t);
RAYLIBWRAPPER_API Vector2 rlw_GetSplinePointBezierQuad(Vector2 p1, Vector2 c2, Vector2 p3, float t);
RAYLIBWRAPPER_API Vector2 rlw_GetSplinePointBezierCubic(Vector2 p1, Vector2 c2, Vector2 c3, Vector2 p4, float t);
RAYLIBWRAPPER_API bool rlw_CheckCollisionRecs(Rectangle rec1, Rectangle rec2);
RAYLIBWRAPPER_API bool rlw_CheckCollisionCircles(Vector2 center1, float radius1, Vector2 center2, float radius2);
RAYLIBWRAPPER_API bool rlw_CheckCollisionCircleRec(Vector2 center, float radius, Rectangle rec);
RAYLIBWRAPPER_API bool rlw_CheckCollisionPointRec(Vector2 point, Rectangle rec);
RAYLIBWRAPPER_API bool rlw_CheckCollisionPointCircle(Vector2 point, Vector2 center, float radius);
RAYLIBWRAPPER_API bool rlw_CheckCollisionPointTriangle(Vector2 point, Vector2 p1, Vector2 p2, Vector2 p3);
RAYLIBWRAPPER_API bool rlw_CheckCollisionPointPoly(Vector2 point, Vector2 *points, int pointCount);
RAYLIBWRAPPER_API bool rlw_CheckCollisionLines(Vector2 startPos1, Vector2 endPos1, Vector2 startPos2, Vector2 endPos2, Vector2 *collisionPoint);
RAYLIBWRAPPER_API bool rlw_CheckCollisionPointLine(Vector2 point, Vector2 p1, Vector2 p2, int threshold);
RAYLIBWRAPPER_API Rectangle rlw_GetCollisionRec(Rectangle rec1, Rectangle rec2);
RAYLIBWRAPPER_API Image rlw_LoadImage(const char *fileName);
RAYLIBWRAPPER_API Image rlw_LoadImageRaw(const char *fileName, int width, int height, int format, int headerSize);
RAYLIBWRAPPER_API Image rlw_LoadImageAnim(const char *fileName, int *frames);
RAYLIBWRAPPER_API Image rlw_LoadImageFromMemory(const char *fileType, const unsigned char *fileData, int dataSize);
RAYLIBWRAPPER_API Image rlw_LoadImageFromTexture(Texture2D texture);
RAYLIBWRAPPER_API Image rlw_LoadImageFromScreen(void);
RAYLIBWRAPPER_API bool rlw_IsImageValid(Image image);
RAYLIBWRAPPER_API void rlw_UnloadImage(Image image);
RAYLIBWRAPPER_API bool rlw_ExportImage(Image image, const char *fileName);
RAYLIBWRAPPER_API bool rlw_ExportImageAsCode(Image image, const char *fileName);
RAYLIBWRAPPER_API Image rlw_GenImageColor(int width, int height, Color color);
RAYLIBWRAPPER_API Image rlw_GenImageGradientLinear(int width, int height, int direction, Color start, Color end);
RAYLIBWRAPPER_API Image rlw_GenImageGradientRadial(int width, int height, float density, Color inner, Color outer);
RAYLIBWRAPPER_API Image rlw_GenImageGradientSquare(int width, int height, float density, Color inner, Color outer);
RAYLIBWRAPPER_API Image rlw_GenImageChecked(int width, int height, int checksX, int checksY, Color col1, Color col2);
RAYLIBWRAPPER_API Image rlw_GenImageWhiteNoise(int width, int height, float factor);
RAYLIBWRAPPER_API Image rlw_GenImagePerlinNoise(int width, int height, int offsetX, int offsetY, float scale);
RAYLIBWRAPPER_API Image rlw_GenImageCellular(int width, int height, int tileSize);
RAYLIBWRAPPER_API Image rlw_GenImageText(int width, int height, const char *text);
RAYLIBWRAPPER_API Image rlw_ImageCopy(Image image);
RAYLIBWRAPPER_API Image rlw_ImageFromImage(Image image, Rectangle rec);
RAYLIBWRAPPER_API Image rlw_ImageText(const char *text, int fontSize, Color color);
RAYLIBWRAPPER_API Image rlw_ImageTextEx(Font font, const char *text, float fontSize, float spacing, Color tint);
RAYLIBWRAPPER_API void rlw_ImageFormat(Image *image, int newFormat);
RAYLIBWRAPPER_API void rlw_ImageToPOT(Image *image, Color fill);
RAYLIBWRAPPER_API void rlw_ImageCrop(Image *image, Rectangle crop);
RAYLIBWRAPPER_API void rlw_ImageAlphaCrop(Image *image, float threshold);
RAYLIBWRAPPER_API void rlw_ImageAlphaClear(Image *image, Color color, float threshold);
RAYLIBWRAPPER_API void rlw_ImageAlphaMask(Image *image, Image alphaMask);
RAYLIBWRAPPER_API void rlw_ImageAlphaPremultiply(Image *image);
RAYLIBWRAPPER_API void rlw_ImageBlurGaussian(Image *image, int blurSize);
RAYLIBWRAPPER_API void rlw_ImageResize(Image *image, int newWidth, int newHeight);
RAYLIBWRAPPER_API void rlw_ImageResizeNN(Image *image, int newWidth, int newHeight);
RAYLIBWRAPPER_API void rlw_ImageResizeCanvas(Image *image, int newWidth, int newHeight, int offsetX, int offsetY, Color fill);
RAYLIBWRAPPER_API void rlw_ImageMipmaps(Image *image);
RAYLIBWRAPPER_API void rlw_ImageDither(Image *image, int rBpp, int gBpp, int bBpp, int aBpp);
RAYLIBWRAPPER_API void rlw_ImageFlipVertical(Image *image);
RAYLIBWRAPPER_API void rlw_ImageFlipHorizontal(Image *image);
RAYLIBWRAPPER_API void rlw_ImageRotate(Image *image, int degrees);
RAYLIBWRAPPER_API void rlw_ImageRotateCW(Image *image);
RAYLIBWRAPPER_API void rlw_ImageRotateCCW(Image *image);
RAYLIBWRAPPER_API void rlw_ImageColorTint(Image *image, Color color);
RAYLIBWRAPPER_API void rlw_ImageColorInvert(Image *image);
RAYLIBWRAPPER_API void rlw_ImageColorGrayscale(Image *image);
RAYLIBWRAPPER_API void rlw_ImageColorContrast(Image *image, float contrast);
RAYLIBWRAPPER_API void rlw_ImageColorBrightness(Image *image, int brightness);
RAYLIBWRAPPER_API void rlw_ImageColorReplace(Image *image, Color color, Color replace);
RAYLIBWRAPPER_API void rlw_UnloadImageColors(Color *colors);
RAYLIBWRAPPER_API void rlw_UnloadImagePalette(Color *colors);
RAYLIBWRAPPER_API Rectangle rlw_GetImageAlphaBorder(Image image, float threshold);
RAYLIBWRAPPER_API Color rlw_GetImageColor(Image image, int x, int y);
RAYLIBWRAPPER_API void rlw_ImageClearBackground(Image *dst, Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawPixel(Image *dst, int posX, int posY, Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawPixelV(Image *dst, Vector2 position, Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawLine(Image *dst, int startPosX, int startPosY, int endPosX, int endPosY, Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawLineV(Image *dst, Vector2 start, Vector2 end, Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawCircle(Image *dst, int centerX, int centerY, int radius, Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawCircleV(Image *dst, Vector2 center, int radius, Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawCircleLines(Image *dst, int centerX, int centerY, int radius, Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawCircleLinesV(Image *dst, Vector2 center, int radius, Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawRectangle(Image *dst, int posX, int posY, int width, int height, Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawRectangleV(Image *dst, Vector2 position, Vector2 size, Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawRectangleRec(Image *dst, Rectangle rec, Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawRectangleLines(Image *dst, Rectangle rec, int thick, Color color);
RAYLIBWRAPPER_API void rlw_ImageDraw(Image *dst, Image src, Rectangle srcRec, Rectangle dstRec, Color tint);
RAYLIBWRAPPER_API void rlw_ImageDrawText(Image *dst, const char *text, int posX, int posY, int fontSize, Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawTextEx(Image *dst, Font font, const char *text, Vector2 position, float fontSize, float spacing, Color tint);
RAYLIBWRAPPER_API Texture2D rlw_LoadTexture(const char *fileName);
RAYLIBWRAPPER_API Texture2D rlw_LoadTextureFromImage(Image image);
RAYLIBWRAPPER_API TextureCubemap rlw_LoadTextureCubemap(Image image, int layout);
RAYLIBWRAPPER_API RenderTexture2D rlw_LoadRenderTexture(int width, int height);
RAYLIBWRAPPER_API bool rlw_IsTextureValid(Texture2D texture);
RAYLIBWRAPPER_API void rlw_UnloadTexture(Texture2D texture);
RAYLIBWRAPPER_API bool rlw_IsRenderTextureValid(RenderTexture2D target);
RAYLIBWRAPPER_API void rlw_UnloadRenderTexture(RenderTexture2D target);
RAYLIBWRAPPER_API void rlw_UpdateTexture(Texture2D texture, const void *pixels);
RAYLIBWRAPPER_API void rlw_UpdateTextureRec(Texture2D texture, Rectangle rec, const void *pixels);
RAYLIBWRAPPER_API void rlw_GenTextureMipmaps(Texture2D *texture);
RAYLIBWRAPPER_API void rlw_SetTextureFilter(Texture2D texture, int filter);
RAYLIBWRAPPER_API void rlw_SetTextureWrap(Texture2D texture, int wrap);
RAYLIBWRAPPER_API void rlw_DrawTexture(Texture2D texture, int posX, int posY, Color tint);
RAYLIBWRAPPER_API void rlw_DrawTextureV(Texture2D texture, Vector2 position, Color tint);
RAYLIBWRAPPER_API void rlw_DrawTextureEx(Texture2D texture, Vector2 position, float rotation, float scale, Color tint);
RAYLIBWRAPPER_API void rlw_DrawTextureRec(Texture2D texture, Rectangle source, Vector2 position, Color tint);
RAYLIBWRAPPER_API void rlw_DrawTexturePro(Texture2D texture, Rectangle source, Rectangle dest, Vector2 origin, float rotation, Color tint);
RAYLIBWRAPPER_API void rlw_DrawTextureNPatch(Texture2D texture, NPatchInfo nPatchInfo, Rectangle dest, Vector2 origin, float rotation, Color tint);
RAYLIBWRAPPER_API Color rlw_Fade(Color color, float alpha);
RAYLIBWRAPPER_API int rlw_ColorToInt(Color color);
RAYLIBWRAPPER_API Vector4 rlw_ColorNormalize(Color color);
RAYLIBWRAPPER_API Color rlw_ColorFromNormalized(Vector4 normalized);
RAYLIBWRAPPER_API Vector3 rlw_ColorToHSV(Color color);
RAYLIBWRAPPER_API Color rlw_ColorFromHSV(float hue, float saturation, float value);
RAYLIBWRAPPER_API Color rlw_ColorTint(Color color, Color tint);
RAYLIBWRAPPER_API Color rlw_ColorBrightness(Color color, float factor);
RAYLIBWRAPPER_API Color rlw_ColorContrast(Color color, float contrast);
RAYLIBWRAPPER_API Color rlw_ColorAlpha(Color color, float alpha);
RAYLIBWRAPPER_API Color rlw_ColorAlphaBlend(Color dst, Color src, Color tint);
RAYLIBWRAPPER_API Color rlw_GetColor(unsigned int hexValue);
RAYLIBWRAPPER_API Color rlw_GetPixelColor(void *srcPtr, int format);
RAYLIBWRAPPER_API void rlw_SetPixelColor(void *dstPtr, Color color, int format);
RAYLIBWRAPPER_API int rlw_GetPixelDataSize(int width, int height, int format);
RAYLIBWRAPPER_API Font rlw_GetFontDefault(void);
RAYLIBWRAPPER_API Font rlw_LoadFont(const char *fileName);
RAYLIBWRAPPER_API Font rlw_LoadFontEx(const char *fileName, int fontSize, int *codepoints, int codepointCount);
RAYLIBWRAPPER_API Font rlw_LoadFontFromImage(Image image, Color key, int firstChar);
RAYLIBWRAPPER_API Font rlw_LoadFontFromMemory(const char *fileType, const unsigned char *fileData, int dataSize, int fontSize, int *codepoints, int codepointCount);
RAYLIBWRAPPER_API bool rlw_IsFontValid(Font font);
RAYLIBWRAPPER_API Image rlw_GenImageFontAtlas(const GlyphInfo *glyphs, Rectangle **glyphRecs, int glyphCount, int fontSize, int padding, int packMethod);
RAYLIBWRAPPER_API void rlw_UnloadFontData(GlyphInfo *glyphs, int glyphCount);
RAYLIBWRAPPER_API void rlw_UnloadFont(Font font);
RAYLIBWRAPPER_API bool rlw_ExportFontAsCode(Font font, const char *fileName);
RAYLIBWRAPPER_API void rlw_DrawFPS(int posX, int posY);
RAYLIBWRAPPER_API void rlw_DrawText(const char *text, int posX, int posY, int fontSize, Color color);
RAYLIBWRAPPER_API void rlw_DrawTextEx(Font font, const char *text, Vector2 position, float fontSize, float spacing, Color tint);
RAYLIBWRAPPER_API void rlw_DrawTextPro(Font font, const char *text, Vector2 position, Vector2 origin, float rotation, float fontSize, float spacing, Color tint);
RAYLIBWRAPPER_API void rlw_DrawTextCodepoint(Font font, int codepoint, Vector2 position, float fontSize, Color tint);
RAYLIBWRAPPER_API void rlw_DrawTextCodepoints(Font font, const int *codepoints, int codepointCount, Vector2 position, float fontSize, float spacing, Color tint);
RAYLIBWRAPPER_API void rlw_SetTextLineSpacing(int spacing);
RAYLIBWRAPPER_API int rlw_MeasureText(const char *text, int fontSize);
RAYLIBWRAPPER_API Vector2 rlw_MeasureTextEx(Font font, const char *text, float fontSize, float spacing);
RAYLIBWRAPPER_API int rlw_GetGlyphIndex(Font font, int codepoint);
RAYLIBWRAPPER_API GlyphInfo rlw_GetGlyphInfo(Font font, int codepoint);
RAYLIBWRAPPER_API Rectangle rlw_GetGlyphAtlasRec(Font font, int codepoint);
RAYLIBWRAPPER_API void rlw_UnloadUTF8(char *text);
RAYLIBWRAPPER_API void rlw_UnloadCodepoints(int *codepoints);
RAYLIBWRAPPER_API int rlw_GetCodepointCount(const char *text);
RAYLIBWRAPPER_API int rlw_GetCodepoint(const char *text, int *codepointSize);
RAYLIBWRAPPER_API int rlw_GetCodepointNext(const char *text, int *codepointSize);
RAYLIBWRAPPER_API int rlw_GetCodepointPrevious(const char *text, int *codepointSize);
RAYLIBWRAPPER_API int rlw_TextCopy(char *dst, const char *src);
RAYLIBWRAPPER_API bool rlw_TextIsEqual(const char *text1, const char *text2);
RAYLIBWRAPPER_API unsigned int rlw_TextLength(const char *text);
RAYLIBWRAPPER_API void rlw_TextAppend(char *text, const char *append, int *position);
RAYLIBWRAPPER_API int rlw_TextFindIndex(const char *text, const char *find);
RAYLIBWRAPPER_API int rlw_TextToInteger(const char *text);
RAYLIBWRAPPER_API void rlw_DrawLine3D(Vector3 startPos, Vector3 endPos, Color color);
RAYLIBWRAPPER_API void rlw_DrawPoint3D(Vector3 position, Color color);
RAYLIBWRAPPER_API void rlw_DrawCircle3D(Vector3 center, float radius, Vector3 rotationAxis, float rotationAngle, Color color);
RAYLIBWRAPPER_API void rlw_DrawTriangle3D(Vector3 v1, Vector3 v2, Vector3 v3, Color color);
RAYLIBWRAPPER_API void rlw_DrawTriangleStrip3D(Vector3 *points, int pointCount, Color color);
RAYLIBWRAPPER_API void rlw_DrawCube(Vector3 position, float width, float height, float length, Color color);
RAYLIBWRAPPER_API void rlw_DrawCubeV(Vector3 position, Vector3 size, Color color);
RAYLIBWRAPPER_API void rlw_DrawCubeWires(Vector3 position, float width, float height, float length, Color color);
RAYLIBWRAPPER_API void rlw_DrawCubeWiresV(Vector3 position, Vector3 size, Color color);
RAYLIBWRAPPER_API void rlw_DrawSphere(Vector3 centerPos, float radius, Color color);
RAYLIBWRAPPER_API void rlw_DrawSphereEx(Vector3 centerPos, float radius, int rings, int slices, Color color);
RAYLIBWRAPPER_API void rlw_DrawSphereWires(Vector3 centerPos, float radius, int rings, int slices, Color color);
RAYLIBWRAPPER_API void rlw_DrawCylinder(Vector3 position, float radiusTop, float radiusBottom, float height, int slices, Color color);
RAYLIBWRAPPER_API void rlw_DrawCylinderEx(Vector3 startPos, Vector3 endPos, float startRadius, float endRadius, int sides, Color color);
RAYLIBWRAPPER_API void rlw_DrawCylinderWires(Vector3 position, float radiusTop, float radiusBottom, float height, int slices, Color color);
RAYLIBWRAPPER_API void rlw_DrawCylinderWiresEx(Vector3 startPos, Vector3 endPos, float startRadius, float endRadius, int sides, Color color);
RAYLIBWRAPPER_API void rlw_DrawCapsule(Vector3 startPos, Vector3 endPos, float radius, int slices, int rings, Color color);
RAYLIBWRAPPER_API void rlw_DrawCapsuleWires(Vector3 startPos, Vector3 endPos, float radius, int slices, int rings, Color color);
RAYLIBWRAPPER_API void rlw_DrawPlane(Vector3 centerPos, Vector2 size, Color color);
RAYLIBWRAPPER_API void rlw_DrawRay(Ray ray, Color color);
RAYLIBWRAPPER_API void rlw_DrawGrid(int slices, float spacing);
RAYLIBWRAPPER_API Model rlw_LoadModel(const char *fileName);
RAYLIBWRAPPER_API Model rlw_LoadModelFromMesh(Mesh mesh);
RAYLIBWRAPPER_API bool rlw_IsModelValid(Model model);
RAYLIBWRAPPER_API void rlw_UnloadModel(Model model);
RAYLIBWRAPPER_API BoundingBox rlw_GetModelBoundingBox(Model model);
RAYLIBWRAPPER_API void rlw_DrawModel(Model model, Vector3 position, float scale, Color tint);
RAYLIBWRAPPER_API void rlw_DrawModelEx(Model model, Vector3 position, Vector3 rotationAxis, float rotationAngle, Vector3 scale, Color tint);
RAYLIBWRAPPER_API void rlw_DrawModelWires(Model model, Vector3 position, float scale, Color tint);
RAYLIBWRAPPER_API void rlw_DrawModelWiresEx(Model model, Vector3 position, Vector3 rotationAxis, float rotationAngle, Vector3 scale, Color tint);
RAYLIBWRAPPER_API void rlw_DrawBoundingBox(BoundingBox box, Color color);
RAYLIBWRAPPER_API void rlw_DrawBillboard(Camera camera, Texture2D texture, Vector3 position, float size, Color tint);
RAYLIBWRAPPER_API void rlw_DrawBillboardRec(Camera camera, Texture2D texture, Rectangle source, Vector3 position, Vector2 size, Color tint);
RAYLIBWRAPPER_API void rlw_DrawBillboardPro(Camera camera, Texture2D texture, Rectangle source, Vector3 position, Vector3 up, Vector2 size, Vector2 origin, float rotation, Color tint);
RAYLIBWRAPPER_API void rlw_UploadMesh(Mesh *mesh, bool dynamic);
RAYLIBWRAPPER_API void rlw_UpdateMeshBuffer(Mesh mesh, int index, const void *data, int dataSize, int offset);
RAYLIBWRAPPER_API void rlw_UnloadMesh(Mesh mesh);
RAYLIBWRAPPER_API void rlw_DrawMesh(Mesh mesh, Material material, Matrix transform);
RAYLIBWRAPPER_API void rlw_DrawMeshInstanced(Mesh mesh, Material material, const Matrix *transforms, int instances);
RAYLIBWRAPPER_API bool rlw_ExportMesh(Mesh mesh, const char *fileName);
RAYLIBWRAPPER_API BoundingBox rlw_GetMeshBoundingBox(Mesh mesh);
RAYLIBWRAPPER_API void rlw_GenMeshTangents(Mesh *mesh);
RAYLIBWRAPPER_API Mesh rlw_GenMeshPoly(int sides, float radius);
RAYLIBWRAPPER_API Mesh rlw_GenMeshPlane(float width, float length, int resX, int resZ);
RAYLIBWRAPPER_API Mesh rlw_GenMeshCube(float width, float height, float length);
RAYLIBWRAPPER_API Mesh rlw_GenMeshSphere(float radius, int rings, int slices);
RAYLIBWRAPPER_API Mesh rlw_GenMeshHemiSphere(float radius, int rings, int slices);
RAYLIBWRAPPER_API Mesh rlw_GenMeshCylinder(float radius, float height, int slices);
RAYLIBWRAPPER_API Mesh rlw_GenMeshCone(float radius, float height, int slices);
RAYLIBWRAPPER_API Mesh rlw_GenMeshTorus(float radius, float size, int radSeg, int sides);
RAYLIBWRAPPER_API Mesh rlw_GenMeshKnot(float radius, float size, int radSeg, int sides);
RAYLIBWRAPPER_API Mesh rlw_GenMeshHeightmap(Image heightmap, Vector3 size);
RAYLIBWRAPPER_API Mesh rlw_GenMeshCubicmap(Image cubicmap, Vector3 cubeSize);
RAYLIBWRAPPER_API Material rlw_LoadMaterialDefault(void);
RAYLIBWRAPPER_API bool rlw_IsMaterialValid(Material material);
RAYLIBWRAPPER_API void rlw_UnloadMaterial(Material material);
RAYLIBWRAPPER_API void rlw_SetMaterialTexture(Material *material, int mapType, Texture2D texture);
RAYLIBWRAPPER_API void rlw_SetModelMeshMaterial(Model *model, int meshId, int materialId);
RAYLIBWRAPPER_API void rlw_UpdateModelAnimation(Model model, ModelAnimation anim, int frame);
RAYLIBWRAPPER_API void rlw_UnloadModelAnimation(ModelAnimation anim);
RAYLIBWRAPPER_API void rlw_UnloadModelAnimations(ModelAnimation *animations, int animCount);
RAYLIBWRAPPER_API bool rlw_IsModelAnimationValid(Model model, ModelAnimation anim);
RAYLIBWRAPPER_API bool rlw_CheckCollisionSpheres(Vector3 center1, float radius1, Vector3 center2, float radius2);
RAYLIBWRAPPER_API bool rlw_CheckCollisionBoxes(BoundingBox box1, BoundingBox box2);
RAYLIBWRAPPER_API bool rlw_CheckCollisionBoxSphere(BoundingBox box, Vector3 center, float radius);
RAYLIBWRAPPER_API RayCollision rlw_GetRayCollisionSphere(Ray ray, Vector3 center, float radius);
RAYLIBWRAPPER_API RayCollision rlw_GetRayCollisionBox(Ray ray, BoundingBox box);
RAYLIBWRAPPER_API RayCollision rlw_GetRayCollisionMesh(Ray ray, Mesh mesh, Matrix transform);
RAYLIBWRAPPER_API RayCollision rlw_GetRayCollisionTriangle(Ray ray, Vector3 p1, Vector3 p2, Vector3 p3);
RAYLIBWRAPPER_API RayCollision rlw_GetRayCollisionQuad(Ray ray, Vector3 p1, Vector3 p2, Vector3 p3, Vector3 p4);
RAYLIBWRAPPER_API void rlw_InitAudioDevice(void);
RAYLIBWRAPPER_API void rlw_CloseAudioDevice(void);
RAYLIBWRAPPER_API bool rlw_IsAudioDeviceReady(void);
RAYLIBWRAPPER_API void rlw_SetMasterVolume(float volume);
RAYLIBWRAPPER_API float rlw_GetMasterVolume(void);
RAYLIBWRAPPER_API Wave rlw_LoadWave(const char *fileName);
RAYLIBWRAPPER_API Wave rlw_LoadWaveFromMemory(const char *fileType, const unsigned char *fileData, int dataSize);
RAYLIBWRAPPER_API bool rlw_IsWaveValid(Wave wave);
RAYLIBWRAPPER_API Sound rlw_LoadSound(const char *fileName);
RAYLIBWRAPPER_API Sound rlw_LoadSoundFromWave(Wave wave);
RAYLIBWRAPPER_API Sound rlw_LoadSoundAlias(Sound source);
RAYLIBWRAPPER_API bool rlw_IsSoundValid(Sound sound);
RAYLIBWRAPPER_API void rlw_UpdateSound(Sound sound, const void *data, int sampleCount);
RAYLIBWRAPPER_API void rlw_UnloadWave(Wave wave);
RAYLIBWRAPPER_API void rlw_UnloadSound(Sound sound);
RAYLIBWRAPPER_API void rlw_UnloadSoundAlias(Sound alias);
RAYLIBWRAPPER_API bool rlw_ExportWave(Wave wave, const char *fileName);
RAYLIBWRAPPER_API bool rlw_ExportWaveAsCode(Wave wave, const char *fileName);
RAYLIBWRAPPER_API void rlw_PlaySound(Sound sound);
RAYLIBWRAPPER_API void rlw_StopSound(Sound sound);
RAYLIBWRAPPER_API void rlw_PauseSound(Sound sound);
RAYLIBWRAPPER_API void rlw_ResumeSound(Sound sound);
RAYLIBWRAPPER_API bool rlw_IsSoundPlaying(Sound sound);
RAYLIBWRAPPER_API void rlw_SetSoundVolume(Sound sound, float volume);
RAYLIBWRAPPER_API void rlw_SetSoundPitch(Sound sound, float pitch);
RAYLIBWRAPPER_API void rlw_SetSoundPan(Sound sound, float pan);
RAYLIBWRAPPER_API Wave rlw_WaveCopy(Wave wave);
RAYLIBWRAPPER_API void rlw_WaveCrop(Wave *wave, int initSample, int finalSample);
RAYLIBWRAPPER_API void rlw_WaveFormat(Wave *wave, int sampleRate, int sampleSize, int channels);
RAYLIBWRAPPER_API void rlw_UnloadWaveSamples(float *samples);
RAYLIBWRAPPER_API Music rlw_LoadMusicStream(const char *fileName);
RAYLIBWRAPPER_API Music rlw_LoadMusicStreamFromMemory(const char *fileType, const unsigned char *data, int dataSize);
RAYLIBWRAPPER_API bool rlw_IsMusicValid(Music music);
RAYLIBWRAPPER_API void rlw_UnloadMusicStream(Music music);
RAYLIBWRAPPER_API void rlw_PlayMusicStream(Music music);
RAYLIBWRAPPER_API bool rlw_IsMusicStreamPlaying(Music music);
RAYLIBWRAPPER_API void rlw_UpdateMusicStream(Music music);
RAYLIBWRAPPER_API void rlw_StopMusicStream(Music music);
RAYLIBWRAPPER_API void rlw_PauseMusicStream(Music music);
RAYLIBWRAPPER_API void rlw_ResumeMusicStream(Music music);
RAYLIBWRAPPER_API void rlw_SeekMusicStream(Music music, float position);
RAYLIBWRAPPER_API void rlw_SetMusicVolume(Music music, float volume);
RAYLIBWRAPPER_API void rlw_SetMusicPitch(Music music, float pitch);
RAYLIBWRAPPER_API void rlw_SetMusicPan(Music music, float pan);
RAYLIBWRAPPER_API float rlw_GetMusicTimeLength(Music music);
RAYLIBWRAPPER_API float rlw_GetMusicTimePlayed(Music music);
RAYLIBWRAPPER_API AudioStream rlw_LoadAudioStream(unsigned int sampleRate, unsigned int sampleSize, unsigned int channels);
RAYLIBWRAPPER_API bool rlw_IsAudioStreamValid(AudioStream stream);
RAYLIBWRAPPER_API void rlw_UnloadAudioStream(AudioStream stream);
RAYLIBWRAPPER_API void rlw_UpdateAudioStream(AudioStream stream, const void *data, int frameCount);
RAYLIBWRAPPER_API bool rlw_IsAudioStreamProcessed(AudioStream stream);
RAYLIBWRAPPER_API void rlw_PlayAudioStream(AudioStream stream);
RAYLIBWRAPPER_API void rlw_PauseAudioStream(AudioStream stream);
RAYLIBWRAPPER_API void rlw_ResumeAudioStream(AudioStream stream);
RAYLIBWRAPPER_API bool rlw_IsAudioStreamPlaying(AudioStream stream);
RAYLIBWRAPPER_API void rlw_StopAudioStream(AudioStream stream);
RAYLIBWRAPPER_API void rlw_SetAudioStreamVolume(AudioStream stream, float volume);
RAYLIBWRAPPER_API void rlw_SetAudioStreamPitch(AudioStream stream, float pitch);
RAYLIBWRAPPER_API void rlw_SetAudioStreamPan(AudioStream stream, float pan);
RAYLIBWRAPPER_API void rlw_SetAudioStreamBufferSizeDefault(int size);
RAYLIBWRAPPER_API void rlw_SetAudioStreamCallback(AudioStream stream, AudioCallback callback);
RAYLIBWRAPPER_API void rlw_AttachAudioStreamProcessor(AudioStream stream, AudioCallback processor);
RAYLIBWRAPPER_API void rlw_DetachAudioStreamProcessor(AudioStream stream, AudioCallback processor);
RAYLIBWRAPPER_API void rlw_AttachAudioMixedProcessor(AudioCallback processor);
RAYLIBWRAPPER_API void rlw_DetachAudioMixedProcessor(AudioCallback processor);

#ifdef __cplusplus
} // extern "C"
#endif