#pragma once
#include <RaylibWrapper/export.h>
#include <RaylibWrapper/RaylibWrapper.hpp>

#if defined(RAYLIBWRAPPER_SHARED_EXPORT)
#  define RAYLIBWRAPPER_API RAYLIBWRAPPER_SHARED_EXPORT
#elif defined(RAYLIBWRAPPER_STATIC_EXPORT)
#  define RAYLIBWRAPPER_API RAYLIBWRAPPER_STATIC_EXPORT
#else
#  define RAYLIBWRAPPER_API
#endif

#ifdef __cplusplus
extern "C" {
#endif

RAYLIBWRAPPER_API void rlw_InitWindow(int width, int height, const char *title);
RAYLIBWRAPPER_API void rlw_CloseWindow(void);
RAYLIBWRAPPER_API bool rlw_WindowShouldClose(void);
RAYLIBWRAPPER_API bool rlw_IsWindowReady(void);
RAYLIBWRAPPER_API bool rlw_IsWindowFullscreen(void);
RAYLIBWRAPPER_API bool rlw_IsWindowHidden(void);
RAYLIBWRAPPER_API bool rlw_IsWindowMinimized(void);
RAYLIBWRAPPER_API bool rlw_IsWindowMaximized(void);
RAYLIBWRAPPER_API bool rlw_IsWindowFocused(void);
RAYLIBWRAPPER_API bool rlw_IsWindowResized(void);
RAYLIBWRAPPER_API bool rlw_IsWindowState(unsigned int flag);
RAYLIBWRAPPER_API void rlw_SetWindowState(unsigned int flags);
RAYLIBWRAPPER_API void rlw_ClearWindowState(unsigned int flags);
RAYLIBWRAPPER_API void rlw_ToggleFullscreen(void);
RAYLIBWRAPPER_API void rlw_ToggleBorderlessWindowed(void);
RAYLIBWRAPPER_API void rlw_MaximizeWindow(void);
RAYLIBWRAPPER_API void rlw_MinimizeWindow(void);
RAYLIBWRAPPER_API void rlw_RestoreWindow(void);
RAYLIBWRAPPER_API void rlw_SetWindowIcon(rlw::Image image);
RAYLIBWRAPPER_API void rlw_SetWindowIcons(rlw::Image *images, int count);
RAYLIBWRAPPER_API void rlw_SetWindowTitle(const char *title);
RAYLIBWRAPPER_API void rlw_SetWindowPosition(int x, int y);
RAYLIBWRAPPER_API void rlw_SetWindowMonitor(int monitor);
RAYLIBWRAPPER_API void rlw_SetWindowMinSize(int width, int height);
RAYLIBWRAPPER_API void rlw_SetWindowMaxSize(int width, int height);
RAYLIBWRAPPER_API void rlw_SetWindowSize(int width, int height);
RAYLIBWRAPPER_API void rlw_SetWindowOpacity(float opacity);
RAYLIBWRAPPER_API void rlw_SetWindowFocused(void);
RAYLIBWRAPPER_API int rlw_GetScreenWidth(void);
RAYLIBWRAPPER_API int rlw_GetScreenHeight(void);
RAYLIBWRAPPER_API int rlw_GetRenderWidth(void);
RAYLIBWRAPPER_API int rlw_GetRenderHeight(void);
RAYLIBWRAPPER_API int rlw_GetMonitorCount(void);
RAYLIBWRAPPER_API int rlw_GetCurrentMonitor(void);
RAYLIBWRAPPER_API rlw::Vector2 rlw_GetMonitorPosition(int monitor);
RAYLIBWRAPPER_API int rlw_GetMonitorWidth(int monitor);
RAYLIBWRAPPER_API int rlw_GetMonitorHeight(int monitor);
RAYLIBWRAPPER_API int rlw_GetMonitorPhysicalWidth(int monitor);
RAYLIBWRAPPER_API int rlw_GetMonitorPhysicalHeight(int monitor);
RAYLIBWRAPPER_API int rlw_GetMonitorRefreshRate(int monitor);
RAYLIBWRAPPER_API rlw::Vector2 rlw_GetWindowPosition(void);
RAYLIBWRAPPER_API rlw::Vector2 rlw_GetWindowScaleDPI(void);
RAYLIBWRAPPER_API void rlw_SetClipboardText(const char *text);
RAYLIBWRAPPER_API void rlw_EnableEventWaiting(void);
RAYLIBWRAPPER_API void rlw_DisableEventWaiting(void);
RAYLIBWRAPPER_API void rlw_ShowCursor(void);
RAYLIBWRAPPER_API void rlw_HideCursor(void);
RAYLIBWRAPPER_API bool rlw_IsCursorHidden(void);
RAYLIBWRAPPER_API void rlw_EnableCursor(void);
RAYLIBWRAPPER_API void rlw_DisableCursor(void);
RAYLIBWRAPPER_API bool rlw_IsCursorOnScreen(void);
RAYLIBWRAPPER_API void rlw_ClearBackground(rlw::Color color);
RAYLIBWRAPPER_API void rlw_BeginDrawing(void);
RAYLIBWRAPPER_API void rlw_EndDrawing(void);
RAYLIBWRAPPER_API void rlw_BeginMode2D(rlw::Camera2D camera);
RAYLIBWRAPPER_API void rlw_EndMode2D(void);
RAYLIBWRAPPER_API void rlw_BeginMode3D(rlw::Camera3D camera);
RAYLIBWRAPPER_API void rlw_EndMode3D(void);
RAYLIBWRAPPER_API void rlw_BeginTextureMode(rlw::RenderTexture2D target);
RAYLIBWRAPPER_API void rlw_EndTextureMode(void);
RAYLIBWRAPPER_API void rlw_BeginShaderMode(rlw::Shader shader);
RAYLIBWRAPPER_API void rlw_EndShaderMode(void);
RAYLIBWRAPPER_API void rlw_BeginBlendMode(int mode);
RAYLIBWRAPPER_API void rlw_EndBlendMode(void);
RAYLIBWRAPPER_API void rlw_BeginScissorMode(int x, int y, int width, int height);
RAYLIBWRAPPER_API void rlw_EndScissorMode(void);
RAYLIBWRAPPER_API void rlw_BeginVrStereoMode(rlw::VrStereoConfig config);
RAYLIBWRAPPER_API void rlw_EndVrStereoMode(void);
RAYLIBWRAPPER_API rlw::VrStereoConfig rlw_LoadVrStereoConfig(rlw::VrDeviceInfo device);
RAYLIBWRAPPER_API void rlw_UnloadVrStereoConfig(rlw::VrStereoConfig config);
RAYLIBWRAPPER_API rlw::Shader rlw_LoadShader(const char *vsFileName, const char *fsFileName);
RAYLIBWRAPPER_API rlw::Shader rlw_LoadShaderFromMemory(const char *vsCode, const char *fsCode);
RAYLIBWRAPPER_API bool rlw_IsShaderValid(rlw::Shader shader);
RAYLIBWRAPPER_API int rlw_GetShaderLocation(rlw::Shader shader, const char *uniformName);
RAYLIBWRAPPER_API int rlw_GetShaderLocationAttrib(rlw::Shader shader, const char *attribName);
RAYLIBWRAPPER_API void rlw_SetShaderValue(rlw::Shader shader, int locIndex, const void *value, int uniformType);
RAYLIBWRAPPER_API void rlw_SetShaderValueV(rlw::Shader shader, int locIndex, const void *value, int uniformType, int count);
RAYLIBWRAPPER_API void rlw_SetShaderValueMatrix(rlw::Shader shader, int locIndex, rlw::Matrix mat);
RAYLIBWRAPPER_API void rlw_SetShaderValueTexture(rlw::Shader shader, int locIndex, rlw::Texture2D texture);
RAYLIBWRAPPER_API void rlw_UnloadShader(rlw::Shader shader);
RAYLIBWRAPPER_API rlw::Ray rlw_GetScreenToWorldRay(rlw::Vector2 mousePosition, rlw::Camera camera);
RAYLIBWRAPPER_API rlw::Matrix rlw_GetCameraMatrix(rlw::Camera camera);
RAYLIBWRAPPER_API rlw::Matrix rlw_GetCameraMatrix2D(rlw::Camera2D camera);
RAYLIBWRAPPER_API rlw::Vector2 rlw_GetWorldToScreen(rlw::Vector3 position, rlw::Camera camera);
RAYLIBWRAPPER_API rlw::Vector2 rlw_GetScreenToWorld2D(rlw::Vector2 position, rlw::Camera2D camera);
RAYLIBWRAPPER_API rlw::Vector2 rlw_GetWorldToScreenEx(rlw::Vector3 position, rlw::Camera camera, int width, int height);
RAYLIBWRAPPER_API rlw::Vector2 rlw_GetWorldToScreen2D(rlw::Vector2 position, rlw::Camera2D camera);
RAYLIBWRAPPER_API void rlw_SetTargetFPS(int fps);
RAYLIBWRAPPER_API float rlw_GetFrameTime(void);
RAYLIBWRAPPER_API double rlw_GetTime(void);
RAYLIBWRAPPER_API int rlw_GetFPS(void);
RAYLIBWRAPPER_API void rlw_SwapScreenBuffer(void);
RAYLIBWRAPPER_API void rlw_PollInputEvents(void);
RAYLIBWRAPPER_API void rlw_WaitTime(double seconds);
RAYLIBWRAPPER_API void rlw_SetRandomSeed(unsigned int seed);
RAYLIBWRAPPER_API int rlw_GetRandomValue(int min, int max);
RAYLIBWRAPPER_API void rlw_UnloadRandomSequence(int *sequence);
RAYLIBWRAPPER_API void rlw_TakeScreenshot(const char *fileName);
RAYLIBWRAPPER_API void rlw_SetConfigFlags(unsigned int flags);
RAYLIBWRAPPER_API void rlw_OpenURL(const char *url);
RAYLIBWRAPPER_API void rlw_TraceLog(int logLevel, const char *text, ...);
RAYLIBWRAPPER_API void rlw_SetTraceLogLevel(int logLevel);
RAYLIBWRAPPER_API void rlw_MemFree(void *ptr);
RAYLIBWRAPPER_API void rlw_SetTraceLogCallback(rlw::TraceLogCallback callback);
RAYLIBWRAPPER_API void rlw_SetLoadFileDataCallback(rlw::LoadFileDataCallback callback);
RAYLIBWRAPPER_API void rlw_SetSaveFileDataCallback(rlw::SaveFileDataCallback callback);
RAYLIBWRAPPER_API void rlw_SetLoadFileTextCallback(rlw::LoadFileTextCallback callback);
RAYLIBWRAPPER_API void rlw_SetSaveFileTextCallback(rlw::SaveFileTextCallback callback);
RAYLIBWRAPPER_API void rlw_UnloadFileData(unsigned char *data);
RAYLIBWRAPPER_API bool rlw_SaveFileData(const char *fileName, void *data, int dataSize);
RAYLIBWRAPPER_API bool rlw_ExportDataAsCode(const unsigned char *data, int dataSize, const char *fileName);
RAYLIBWRAPPER_API void rlw_UnloadFileText(char *text);
RAYLIBWRAPPER_API bool rlw_SaveFileText(const char *fileName, char *text);
RAYLIBWRAPPER_API bool rlw_FileExists(const char *fileName);
RAYLIBWRAPPER_API bool rlw_DirectoryExists(const char *dirPath);
RAYLIBWRAPPER_API bool rlw_IsFileExtension(const char *fileName, const char *ext);
RAYLIBWRAPPER_API int rlw_GetFileLength(const char *fileName);
RAYLIBWRAPPER_API bool rlw_ChangeDirectory(const char *dir);
RAYLIBWRAPPER_API bool rlw_IsPathFile(const char *path);
RAYLIBWRAPPER_API rlw::FilePathList rlw_LoadDirectoryFiles(const char *dirPath);
RAYLIBWRAPPER_API rlw::FilePathList rlw_LoadDirectoryFilesEx(const char *basePath, const char *filter, bool scanSubdirs);
RAYLIBWRAPPER_API void rlw_UnloadDirectoryFiles(rlw::FilePathList files);
RAYLIBWRAPPER_API bool rlw_IsFileDropped(void);
RAYLIBWRAPPER_API rlw::FilePathList rlw_LoadDroppedFiles(void);
RAYLIBWRAPPER_API void rlw_UnloadDroppedFiles(rlw::FilePathList files);
RAYLIBWRAPPER_API long rlw_GetFileModTime(const char *fileName);
RAYLIBWRAPPER_API rlw::AutomationEventList rlw_LoadAutomationEventList(const char *fileName);
RAYLIBWRAPPER_API void rlw_UnloadAutomationEventList(rlw::AutomationEventList list);
RAYLIBWRAPPER_API bool rlw_ExportAutomationEventList(rlw::AutomationEventList list, const char *fileName);
RAYLIBWRAPPER_API void rlw_SetAutomationEventList(rlw::AutomationEventList *list);
RAYLIBWRAPPER_API void rlw_SetAutomationEventBaseFrame(int frame);
RAYLIBWRAPPER_API void rlw_StartAutomationEventRecording(void);
RAYLIBWRAPPER_API void rlw_StopAutomationEventRecording(void);
RAYLIBWRAPPER_API void rlw_PlayAutomationEvent(rlw::AutomationEvent event);
RAYLIBWRAPPER_API bool rlw_IsKeyPressed(int key);
RAYLIBWRAPPER_API bool rlw_IsKeyPressedRepeat(int key);
RAYLIBWRAPPER_API bool rlw_IsKeyDown(int key);
RAYLIBWRAPPER_API bool rlw_IsKeyReleased(int key);
RAYLIBWRAPPER_API bool rlw_IsKeyUp(int key);
RAYLIBWRAPPER_API int rlw_GetKeyPressed(void);
RAYLIBWRAPPER_API int rlw_GetCharPressed(void);
RAYLIBWRAPPER_API void rlw_SetExitKey(int key);
RAYLIBWRAPPER_API bool rlw_IsGamepadAvailable(int gamepad);
RAYLIBWRAPPER_API bool rlw_IsGamepadButtonPressed(int gamepad, int button);
RAYLIBWRAPPER_API bool rlw_IsGamepadButtonDown(int gamepad, int button);
RAYLIBWRAPPER_API bool rlw_IsGamepadButtonReleased(int gamepad, int button);
RAYLIBWRAPPER_API bool rlw_IsGamepadButtonUp(int gamepad, int button);
RAYLIBWRAPPER_API int rlw_GetGamepadButtonPressed(void);
RAYLIBWRAPPER_API int rlw_GetGamepadAxisCount(int gamepad);
RAYLIBWRAPPER_API float rlw_GetGamepadAxisMovement(int gamepad, int axis);
RAYLIBWRAPPER_API int rlw_SetGamepadMappings(const char *mappings);
RAYLIBWRAPPER_API bool rlw_IsMouseButtonPressed(int button);
RAYLIBWRAPPER_API bool rlw_IsMouseButtonDown(int button);
RAYLIBWRAPPER_API bool rlw_IsMouseButtonReleased(int button);
RAYLIBWRAPPER_API bool rlw_IsMouseButtonUp(int button);
RAYLIBWRAPPER_API int rlw_GetMouseX(void);
RAYLIBWRAPPER_API int rlw_GetMouseY(void);
RAYLIBWRAPPER_API rlw::Vector2 rlw_GetMousePosition(void);
RAYLIBWRAPPER_API rlw::Vector2 rlw_GetMouseDelta(void);
RAYLIBWRAPPER_API void rlw_SetMousePosition(int x, int y);
RAYLIBWRAPPER_API void rlw_SetMouseOffset(int offsetX, int offsetY);
RAYLIBWRAPPER_API void rlw_SetMouseScale(float scaleX, float scaleY);
RAYLIBWRAPPER_API float rlw_GetMouseWheelMove(void);
RAYLIBWRAPPER_API rlw::Vector2 rlw_GetMouseWheelMoveV(void);
RAYLIBWRAPPER_API void rlw_SetMouseCursor(int cursor);
RAYLIBWRAPPER_API int rlw_GetTouchX(void);
RAYLIBWRAPPER_API int rlw_GetTouchY(void);
RAYLIBWRAPPER_API rlw::Vector2 rlw_GetTouchPosition(int index);
RAYLIBWRAPPER_API int rlw_GetTouchPointId(int index);
RAYLIBWRAPPER_API int rlw_GetTouchPointCount(void);
RAYLIBWRAPPER_API void rlw_SetGesturesEnabled(unsigned int flags);
RAYLIBWRAPPER_API bool rlw_IsGestureDetected(unsigned int gesture);
RAYLIBWRAPPER_API int rlw_GetGestureDetected(void);
RAYLIBWRAPPER_API float rlw_GetGestureHoldDuration(void);
RAYLIBWRAPPER_API rlw::Vector2 rlw_GetGestureDragVector(void);
RAYLIBWRAPPER_API float rlw_GetGestureDragAngle(void);
RAYLIBWRAPPER_API rlw::Vector2 rlw_GetGesturePinchVector(void);
RAYLIBWRAPPER_API float rlw_GetGesturePinchAngle(void);
RAYLIBWRAPPER_API void rlw_UpdateCamera(rlw::Camera *camera, int mode);
RAYLIBWRAPPER_API void rlw_UpdateCameraPro(rlw::Camera *camera, rlw::Vector3 movement, rlw::Vector3 rotation, float zoom);
RAYLIBWRAPPER_API void rlw_SetShapesTexture(rlw::Texture2D texture, rlw::Rectangle source);
RAYLIBWRAPPER_API void rlw_DrawPixel(int posX, int posY, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawPixelV(rlw::Vector2 position, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawLine(int startPosX, int startPosY, int endPosX, int endPosY, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawLineV(rlw::Vector2 startPos, rlw::Vector2 endPos, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawLineEx(rlw::Vector2 startPos, rlw::Vector2 endPos, float thick, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawLineStrip(rlw::Vector2 *points, int pointCount, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawLineBezier(rlw::Vector2 startPos, rlw::Vector2 endPos, float thick, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawCircle(int centerX, int centerY, float radius, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawCircleSector(rlw::Vector2 center, float radius, float startAngle, float endAngle, int segments, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawCircleSectorLines(rlw::Vector2 center, float radius, float startAngle, float endAngle, int segments, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawCircleGradient(int centerX, int centerY, float radius, rlw::Color color1, rlw::Color color2);
RAYLIBWRAPPER_API void rlw_DrawCircleV(rlw::Vector2 center, float radius, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawCircleLines(int centerX, int centerY, float radius, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawCircleLinesV(rlw::Vector2 center, float radius, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawEllipse(int centerX, int centerY, float radiusH, float radiusV, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawEllipseLines(int centerX, int centerY, float radiusH, float radiusV, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawRing(rlw::Vector2 center, float innerRadius, float outerRadius, float startAngle, float endAngle, int segments, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawRingLines(rlw::Vector2 center, float innerRadius, float outerRadius, float startAngle, float endAngle, int segments, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawRectangle(int posX, int posY, int width, int height, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawRectangleV(rlw::Vector2 position, rlw::Vector2 size, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawRectangleRec(rlw::Rectangle rec, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawRectanglePro(rlw::Rectangle rec, rlw::Vector2 origin, float rotation, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawRectangleGradientV(int posX, int posY, int width, int height, rlw::Color color1, rlw::Color color2);
RAYLIBWRAPPER_API void rlw_DrawRectangleGradientH(int posX, int posY, int width, int height, rlw::Color color1, rlw::Color color2);
RAYLIBWRAPPER_API void rlw_DrawRectangleGradientEx(rlw::Rectangle rec, rlw::Color col1, rlw::Color col2, rlw::Color col3, rlw::Color col4);
RAYLIBWRAPPER_API void rlw_DrawRectangleLines(int posX, int posY, int width, int height, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawRectangleLinesEx(rlw::Rectangle rec, float lineThick, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawRectangleRounded(rlw::Rectangle rec, float roundness, int segments, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawRectangleRoundedLines(rlw::Rectangle rec, float roundness, int segments, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawTriangle(rlw::Vector2 v1, rlw::Vector2 v2, rlw::Vector2 v3, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawTriangleLines(rlw::Vector2 v1, rlw::Vector2 v2, rlw::Vector2 v3, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawTriangleFan(rlw::Vector2 *points, int pointCount, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawTriangleStrip(rlw::Vector2 *points, int pointCount, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawPoly(rlw::Vector2 center, int sides, float radius, float rotation, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawPolyLines(rlw::Vector2 center, int sides, float radius, float rotation, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawPolyLinesEx(rlw::Vector2 center, int sides, float radius, float rotation, float lineThick, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawSplineLinear(rlw::Vector2 *points, int pointCount, float thick, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawSplineBasis(rlw::Vector2 *points, int pointCount, float thick, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawSplineCatmullRom(rlw::Vector2 *points, int pointCount, float thick, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawSplineBezierQuadratic(rlw::Vector2 *points, int pointCount, float thick, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawSplineBezierCubic(rlw::Vector2 *points, int pointCount, float thick, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawSplineSegmentLinear(rlw::Vector2 p1, rlw::Vector2 p2, float thick, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawSplineSegmentBasis(rlw::Vector2 p1, rlw::Vector2 p2, rlw::Vector2 p3, rlw::Vector2 p4, float thick, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawSplineSegmentCatmullRom(rlw::Vector2 p1, rlw::Vector2 p2, rlw::Vector2 p3, rlw::Vector2 p4, float thick, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawSplineSegmentBezierQuadratic(rlw::Vector2 p1, rlw::Vector2 c2, rlw::Vector2 p3, float thick, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawSplineSegmentBezierCubic(rlw::Vector2 p1, rlw::Vector2 c2, rlw::Vector2 c3, rlw::Vector2 p4, float thick, rlw::Color color);
RAYLIBWRAPPER_API rlw::Vector2 rlw_GetSplinePointLinear(rlw::Vector2 startPos, rlw::Vector2 endPos, float t);
RAYLIBWRAPPER_API rlw::Vector2 rlw_GetSplinePointBasis(rlw::Vector2 p1, rlw::Vector2 p2, rlw::Vector2 p3, rlw::Vector2 p4, float t);
RAYLIBWRAPPER_API rlw::Vector2 rlw_GetSplinePointCatmullRom(rlw::Vector2 p1, rlw::Vector2 p2, rlw::Vector2 p3, rlw::Vector2 p4, float t);
RAYLIBWRAPPER_API rlw::Vector2 rlw_GetSplinePointBezierQuad(rlw::Vector2 p1, rlw::Vector2 c2, rlw::Vector2 p3, float t);
RAYLIBWRAPPER_API rlw::Vector2 rlw_GetSplinePointBezierCubic(rlw::Vector2 p1, rlw::Vector2 c2, rlw::Vector2 c3, rlw::Vector2 p4, float t);
RAYLIBWRAPPER_API bool rlw_CheckCollisionRecs(rlw::Rectangle rec1, rlw::Rectangle rec2);
RAYLIBWRAPPER_API bool rlw_CheckCollisionCircles(rlw::Vector2 center1, float radius1, rlw::Vector2 center2, float radius2);
RAYLIBWRAPPER_API bool rlw_CheckCollisionCircleRec(rlw::Vector2 center, float radius, rlw::Rectangle rec);
RAYLIBWRAPPER_API bool rlw_CheckCollisionPointRec(rlw::Vector2 point, rlw::Rectangle rec);
RAYLIBWRAPPER_API bool rlw_CheckCollisionPointCircle(rlw::Vector2 point, rlw::Vector2 center, float radius);
RAYLIBWRAPPER_API bool rlw_CheckCollisionPointTriangle(rlw::Vector2 point, rlw::Vector2 p1, rlw::Vector2 p2, rlw::Vector2 p3);
RAYLIBWRAPPER_API bool rlw_CheckCollisionPointPoly(rlw::Vector2 point, rlw::Vector2 *points, int pointCount);
RAYLIBWRAPPER_API bool rlw_CheckCollisionLines(rlw::Vector2 startPos1, rlw::Vector2 endPos1, rlw::Vector2 startPos2, rlw::Vector2 endPos2, rlw::Vector2 *collisionPoint);
RAYLIBWRAPPER_API bool rlw_CheckCollisionPointLine(rlw::Vector2 point, rlw::Vector2 p1, rlw::Vector2 p2, int threshold);
RAYLIBWRAPPER_API rlw::Rectangle rlw_GetCollisionRec(rlw::Rectangle rec1, rlw::Rectangle rec2);
RAYLIBWRAPPER_API rlw::Image rlw_LoadImage(const char *fileName);
RAYLIBWRAPPER_API rlw::Image rlw_LoadImageRaw(const char *fileName, int width, int height, int format, int headerSize);
RAYLIBWRAPPER_API rlw::Image rlw_LoadImageAnim(const char *fileName, int *frames);
RAYLIBWRAPPER_API rlw::Image rlw_LoadImageFromMemory(const char *fileType, const unsigned char *fileData, int dataSize);
RAYLIBWRAPPER_API rlw::Image rlw_LoadImageFromTexture(rlw::Texture2D texture);
RAYLIBWRAPPER_API rlw::Image rlw_LoadImageFromScreen(void);
RAYLIBWRAPPER_API bool rlw_IsImageValid(rlw::Image image);
RAYLIBWRAPPER_API void rlw_UnloadImage(rlw::Image image);
RAYLIBWRAPPER_API bool rlw_ExportImage(rlw::Image image, const char *fileName);
RAYLIBWRAPPER_API bool rlw_ExportImageAsCode(rlw::Image image, const char *fileName);
RAYLIBWRAPPER_API rlw::Image rlw_GenImageColor(int width, int height, rlw::Color color);
RAYLIBWRAPPER_API rlw::Image rlw_GenImageGradientLinear(int width, int height, int direction, rlw::Color start, rlw::Color end);
RAYLIBWRAPPER_API rlw::Image rlw_GenImageGradientRadial(int width, int height, float density, rlw::Color inner, rlw::Color outer);
RAYLIBWRAPPER_API rlw::Image rlw_GenImageGradientSquare(int width, int height, float density, rlw::Color inner, rlw::Color outer);
RAYLIBWRAPPER_API rlw::Image rlw_GenImageChecked(int width, int height, int checksX, int checksY, rlw::Color col1, rlw::Color col2);
RAYLIBWRAPPER_API rlw::Image rlw_GenImageWhiteNoise(int width, int height, float factor);
RAYLIBWRAPPER_API rlw::Image rlw_GenImagePerlinNoise(int width, int height, int offsetX, int offsetY, float scale);
RAYLIBWRAPPER_API rlw::Image rlw_GenImageCellular(int width, int height, int tileSize);
RAYLIBWRAPPER_API rlw::Image rlw_GenImageText(int width, int height, const char *text);
RAYLIBWRAPPER_API rlw::Image rlw_ImageCopy(rlw::Image image);
RAYLIBWRAPPER_API rlw::Image rlw_ImageFromImage(rlw::Image image, rlw::Rectangle rec);
RAYLIBWRAPPER_API rlw::Image rlw_ImageText(const char *text, int fontSize, rlw::Color color);
RAYLIBWRAPPER_API rlw::Image rlw_ImageTextEx(rlw::Font font, const char *text, float fontSize, float spacing, rlw::Color tint);
RAYLIBWRAPPER_API void rlw_ImageFormat(rlw::Image *image, int newFormat);
RAYLIBWRAPPER_API void rlw_ImageToPOT(rlw::Image *image, rlw::Color fill);
RAYLIBWRAPPER_API void rlw_ImageCrop(rlw::Image *image, rlw::Rectangle crop);
RAYLIBWRAPPER_API void rlw_ImageAlphaCrop(rlw::Image *image, float threshold);
RAYLIBWRAPPER_API void rlw_ImageAlphaClear(rlw::Image *image, rlw::Color color, float threshold);
RAYLIBWRAPPER_API void rlw_ImageAlphaMask(rlw::Image *image, rlw::Image alphaMask);
RAYLIBWRAPPER_API void rlw_ImageAlphaPremultiply(rlw::Image *image);
RAYLIBWRAPPER_API void rlw_ImageBlurGaussian(rlw::Image *image, int blurSize);
RAYLIBWRAPPER_API void rlw_ImageResize(rlw::Image *image, int newWidth, int newHeight);
RAYLIBWRAPPER_API void rlw_ImageResizeNN(rlw::Image *image, int newWidth, int newHeight);
RAYLIBWRAPPER_API void rlw_ImageResizeCanvas(rlw::Image *image, int newWidth, int newHeight, int offsetX, int offsetY, rlw::Color fill);
RAYLIBWRAPPER_API void rlw_ImageMipmaps(rlw::Image *image);
RAYLIBWRAPPER_API void rlw_ImageDither(rlw::Image *image, int rBpp, int gBpp, int bBpp, int aBpp);
RAYLIBWRAPPER_API void rlw_ImageFlipVertical(rlw::Image *image);
RAYLIBWRAPPER_API void rlw_ImageFlipHorizontal(rlw::Image *image);
RAYLIBWRAPPER_API void rlw_ImageRotate(rlw::Image *image, int degrees);
RAYLIBWRAPPER_API void rlw_ImageRotateCW(rlw::Image *image);
RAYLIBWRAPPER_API void rlw_ImageRotateCCW(rlw::Image *image);
RAYLIBWRAPPER_API void rlw_ImageColorTint(rlw::Image *image, rlw::Color color);
RAYLIBWRAPPER_API void rlw_ImageColorInvert(rlw::Image *image);
RAYLIBWRAPPER_API void rlw_ImageColorGrayscale(rlw::Image *image);
RAYLIBWRAPPER_API void rlw_ImageColorContrast(rlw::Image *image, float contrast);
RAYLIBWRAPPER_API void rlw_ImageColorBrightness(rlw::Image *image, int brightness);
RAYLIBWRAPPER_API void rlw_ImageColorReplace(rlw::Image *image, rlw::Color color, rlw::Color replace);
RAYLIBWRAPPER_API void rlw_UnloadImageColors(rlw::Color *colors);
RAYLIBWRAPPER_API void rlw_UnloadImagePalette(rlw::Color *colors);
RAYLIBWRAPPER_API rlw::Rectangle rlw_GetImageAlphaBorder(rlw::Image image, float threshold);
RAYLIBWRAPPER_API rlw::Color rlw_GetImageColor(rlw::Image image, int x, int y);
RAYLIBWRAPPER_API void rlw_ImageClearBackground(rlw::Image *dst, rlw::Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawPixel(rlw::Image *dst, int posX, int posY, rlw::Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawPixelV(rlw::Image *dst, rlw::Vector2 position, rlw::Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawLine(rlw::Image *dst, int startPosX, int startPosY, int endPosX, int endPosY, rlw::Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawLineV(rlw::Image *dst, rlw::Vector2 start, rlw::Vector2 end, rlw::Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawCircle(rlw::Image *dst, int centerX, int centerY, int radius, rlw::Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawCircleV(rlw::Image *dst, rlw::Vector2 center, int radius, rlw::Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawCircleLines(rlw::Image *dst, int centerX, int centerY, int radius, rlw::Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawCircleLinesV(rlw::Image *dst, rlw::Vector2 center, int radius, rlw::Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawRectangle(rlw::Image *dst, int posX, int posY, int width, int height, rlw::Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawRectangleV(rlw::Image *dst, rlw::Vector2 position, rlw::Vector2 size, rlw::Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawRectangleRec(rlw::Image *dst, rlw::Rectangle rec, rlw::Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawRectangleLines(rlw::Image *dst, rlw::Rectangle rec, int thick, rlw::Color color);
RAYLIBWRAPPER_API void rlw_ImageDraw(rlw::Image *dst, rlw::Image src, rlw::Rectangle srcRec, rlw::Rectangle dstRec, rlw::Color tint);
RAYLIBWRAPPER_API void rlw_ImageDrawText(rlw::Image *dst, const char *text, int posX, int posY, int fontSize, rlw::Color color);
RAYLIBWRAPPER_API void rlw_ImageDrawTextEx(rlw::Image *dst, rlw::Font font, const char *text, rlw::Vector2 position, float fontSize, float spacing, rlw::Color tint);
RAYLIBWRAPPER_API rlw::Texture2D rlw_LoadTexture(const char *fileName);
RAYLIBWRAPPER_API rlw::Texture2D rlw_LoadTextureFromImage(rlw::Image image);
RAYLIBWRAPPER_API rlw::TextureCubemap rlw_LoadTextureCubemap(rlw::Image image, int layout);
RAYLIBWRAPPER_API rlw::RenderTexture2D rlw_LoadRenderTexture(int width, int height);
RAYLIBWRAPPER_API bool rlw_IsTextureValid(rlw::Texture2D texture);
RAYLIBWRAPPER_API void rlw_UnloadTexture(rlw::Texture2D texture);
RAYLIBWRAPPER_API bool rlw_IsRenderTextureValid(rlw::RenderTexture2D target);
RAYLIBWRAPPER_API void rlw_UnloadRenderTexture(rlw::RenderTexture2D target);
RAYLIBWRAPPER_API void rlw_UpdateTexture(rlw::Texture2D texture, const void *pixels);
RAYLIBWRAPPER_API void rlw_UpdateTextureRec(rlw::Texture2D texture, rlw::Rectangle rec, const void *pixels);
RAYLIBWRAPPER_API void rlw_GenTextureMipmaps(rlw::Texture2D *texture);
RAYLIBWRAPPER_API void rlw_SetTextureFilter(rlw::Texture2D texture, int filter);
RAYLIBWRAPPER_API void rlw_SetTextureWrap(rlw::Texture2D texture, int wrap);
RAYLIBWRAPPER_API void rlw_DrawTexture(rlw::Texture2D texture, int posX, int posY, rlw::Color tint);
RAYLIBWRAPPER_API void rlw_DrawTextureV(rlw::Texture2D texture, rlw::Vector2 position, rlw::Color tint);
RAYLIBWRAPPER_API void rlw_DrawTextureEx(rlw::Texture2D texture, rlw::Vector2 position, float rotation, float scale, rlw::Color tint);
RAYLIBWRAPPER_API void rlw_DrawTextureRec(rlw::Texture2D texture, rlw::Rectangle source, rlw::Vector2 position, rlw::Color tint);
RAYLIBWRAPPER_API void rlw_DrawTexturePro(rlw::Texture2D texture, rlw::Rectangle source, rlw::Rectangle dest, rlw::Vector2 origin, float rotation, rlw::Color tint);
RAYLIBWRAPPER_API void rlw_DrawTextureNPatch(rlw::Texture2D texture, rlw::NPatchInfo nPatchInfo, rlw::Rectangle dest, rlw::Vector2 origin, float rotation, rlw::Color tint);
RAYLIBWRAPPER_API rlw::Color rlw_Fade(rlw::Color color, float alpha);
RAYLIBWRAPPER_API int rlw_ColorToInt(rlw::Color color);
RAYLIBWRAPPER_API rlw::Vector4 rlw_ColorNormalize(rlw::Color color);
RAYLIBWRAPPER_API rlw::Color rlw_ColorFromNormalized(rlw::Vector4 normalized);
RAYLIBWRAPPER_API rlw::Vector3 rlw_ColorToHSV(rlw::Color color);
RAYLIBWRAPPER_API rlw::Color rlw_ColorFromHSV(float hue, float saturation, float value);
RAYLIBWRAPPER_API rlw::Color rlw_ColorTint(rlw::Color color, rlw::Color tint);
RAYLIBWRAPPER_API rlw::Color rlw_ColorBrightness(rlw::Color color, float factor);
RAYLIBWRAPPER_API rlw::Color rlw_ColorContrast(rlw::Color color, float contrast);
RAYLIBWRAPPER_API rlw::Color rlw_ColorAlpha(rlw::Color color, float alpha);
RAYLIBWRAPPER_API rlw::Color rlw_ColorAlphaBlend(rlw::Color dst, rlw::Color src, rlw::Color tint);
RAYLIBWRAPPER_API rlw::Color rlw_GetColor(unsigned int hexValue);
RAYLIBWRAPPER_API rlw::Color rlw_GetPixelColor(void *srcPtr, int format);
RAYLIBWRAPPER_API void rlw_SetPixelColor(void *dstPtr, rlw::Color color, int format);
RAYLIBWRAPPER_API int rlw_GetPixelDataSize(int width, int height, int format);
RAYLIBWRAPPER_API rlw::Font rlw_GetFontDefault(void);
RAYLIBWRAPPER_API rlw::Font rlw_LoadFont(const char *fileName);
RAYLIBWRAPPER_API rlw::Font rlw_LoadFontEx(const char *fileName, int fontSize, int *codepoints, int codepointCount);
RAYLIBWRAPPER_API rlw::Font rlw_LoadFontFromImage(rlw::Image image, rlw::Color key, int firstChar);
RAYLIBWRAPPER_API rlw::Font rlw_LoadFontFromMemory(const char *fileType, const unsigned char *fileData, int dataSize, int fontSize, int *codepoints, int codepointCount);
RAYLIBWRAPPER_API bool rlw_IsFontValid(rlw::Font font);
RAYLIBWRAPPER_API rlw::Image rlw_GenImageFontAtlas(const rlw::GlyphInfo *glyphs, rlw::Rectangle **glyphRecs, int glyphCount, int fontSize, int padding, int packMethod);
RAYLIBWRAPPER_API void rlw_UnloadFontData(rlw::GlyphInfo *glyphs, int glyphCount);
RAYLIBWRAPPER_API void rlw_UnloadFont(rlw::Font font);
RAYLIBWRAPPER_API bool rlw_ExportFontAsCode(rlw::Font font, const char *fileName);
RAYLIBWRAPPER_API void rlw_DrawFPS(int posX, int posY);
RAYLIBWRAPPER_API void rlw_DrawText(const char *text, int posX, int posY, int fontSize, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawTextEx(rlw::Font font, const char *text, rlw::Vector2 position, float fontSize, float spacing, rlw::Color tint);
RAYLIBWRAPPER_API void rlw_DrawTextPro(rlw::Font font, const char *text, rlw::Vector2 position, rlw::Vector2 origin, float rotation, float fontSize, float spacing, rlw::Color tint);
RAYLIBWRAPPER_API void rlw_DrawTextCodepoint(rlw::Font font, int codepoint, rlw::Vector2 position, float fontSize, rlw::Color tint);
RAYLIBWRAPPER_API void rlw_DrawTextCodepoints(rlw::Font font, const int *codepoints, int codepointCount, rlw::Vector2 position, float fontSize, float spacing, rlw::Color tint);
RAYLIBWRAPPER_API void rlw_SetTextLineSpacing(int spacing);
RAYLIBWRAPPER_API int rlw_MeasureText(const char *text, int fontSize);
RAYLIBWRAPPER_API rlw::Vector2 rlw_MeasureTextEx(rlw::Font font, const char *text, float fontSize, float spacing);
RAYLIBWRAPPER_API int rlw_GetGlyphIndex(rlw::Font font, int codepoint);
RAYLIBWRAPPER_API rlw::GlyphInfo rlw_GetGlyphInfo(rlw::Font font, int codepoint);
RAYLIBWRAPPER_API rlw::Rectangle rlw_GetGlyphAtlasRec(rlw::Font font, int codepoint);
RAYLIBWRAPPER_API void rlw_UnloadUTF8(char *text);
RAYLIBWRAPPER_API void rlw_UnloadCodepoints(int *codepoints);
RAYLIBWRAPPER_API int rlw_GetCodepointCount(const char *text);
RAYLIBWRAPPER_API int rlw_GetCodepoint(const char *text, int *codepointSize);
RAYLIBWRAPPER_API int rlw_GetCodepointNext(const char *text, int *codepointSize);
RAYLIBWRAPPER_API int rlw_GetCodepointPrevious(const char *text, int *codepointSize);
RAYLIBWRAPPER_API int rlw_TextCopy(char *dst, const char *src);
RAYLIBWRAPPER_API bool rlw_TextIsEqual(const char *text1, const char *text2);
RAYLIBWRAPPER_API unsigned int rlw_TextLength(const char *text);
RAYLIBWRAPPER_API void rlw_TextAppend(char *text, const char *append, int *position);
RAYLIBWRAPPER_API int rlw_TextFindIndex(const char *text, const char *find);
RAYLIBWRAPPER_API int rlw_TextToInteger(const char *text);
RAYLIBWRAPPER_API void rlw_DrawLine3D(rlw::Vector3 startPos, rlw::Vector3 endPos, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawPoint3D(rlw::Vector3 position, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawCircle3D(rlw::Vector3 center, float radius, rlw::Vector3 rotationAxis, float rotationAngle, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawTriangle3D(rlw::Vector3 v1, rlw::Vector3 v2, rlw::Vector3 v3, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawTriangleStrip3D(rlw::Vector3 *points, int pointCount, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawCube(rlw::Vector3 position, float width, float height, float length, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawCubeV(rlw::Vector3 position, rlw::Vector3 size, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawCubeWires(rlw::Vector3 position, float width, float height, float length, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawCubeWiresV(rlw::Vector3 position, rlw::Vector3 size, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawSphere(rlw::Vector3 centerPos, float radius, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawSphereEx(rlw::Vector3 centerPos, float radius, int rings, int slices, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawSphereWires(rlw::Vector3 centerPos, float radius, int rings, int slices, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawCylinder(rlw::Vector3 position, float radiusTop, float radiusBottom, float height, int slices, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawCylinderEx(rlw::Vector3 startPos, rlw::Vector3 endPos, float startRadius, float endRadius, int sides, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawCylinderWires(rlw::Vector3 position, float radiusTop, float radiusBottom, float height, int slices, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawCylinderWiresEx(rlw::Vector3 startPos, rlw::Vector3 endPos, float startRadius, float endRadius, int sides, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawCapsule(rlw::Vector3 startPos, rlw::Vector3 endPos, float radius, int slices, int rings, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawCapsuleWires(rlw::Vector3 startPos, rlw::Vector3 endPos, float radius, int slices, int rings, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawPlane(rlw::Vector3 centerPos, rlw::Vector2 size, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawRay(rlw::Ray ray, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawGrid(int slices, float spacing);
RAYLIBWRAPPER_API rlw::Model rlw_LoadModel(const char *fileName);
RAYLIBWRAPPER_API rlw::Model rlw_LoadModelFromMesh(rlw::Mesh mesh);
RAYLIBWRAPPER_API bool rlw_IsModelValid(rlw::Model model);
RAYLIBWRAPPER_API void rlw_UnloadModel(rlw::Model model);
RAYLIBWRAPPER_API rlw::BoundingBox rlw_GetModelBoundingBox(rlw::Model model);
RAYLIBWRAPPER_API void rlw_DrawModel(rlw::Model model, rlw::Vector3 position, float scale, rlw::Color tint);
RAYLIBWRAPPER_API void rlw_DrawModelEx(rlw::Model model, rlw::Vector3 position, rlw::Vector3 rotationAxis, float rotationAngle, rlw::Vector3 scale, rlw::Color tint);
RAYLIBWRAPPER_API void rlw_DrawModelWires(rlw::Model model, rlw::Vector3 position, float scale, rlw::Color tint);
RAYLIBWRAPPER_API void rlw_DrawModelWiresEx(rlw::Model model, rlw::Vector3 position, rlw::Vector3 rotationAxis, float rotationAngle, rlw::Vector3 scale, rlw::Color tint);
RAYLIBWRAPPER_API void rlw_DrawBoundingBox(rlw::BoundingBox box, rlw::Color color);
RAYLIBWRAPPER_API void rlw_DrawBillboard(rlw::Camera camera, rlw::Texture2D texture, rlw::Vector3 position, float size, rlw::Color tint);
RAYLIBWRAPPER_API void rlw_DrawBillboardRec(rlw::Camera camera, rlw::Texture2D texture, rlw::Rectangle source, rlw::Vector3 position, rlw::Vector2 size, rlw::Color tint);
RAYLIBWRAPPER_API void rlw_DrawBillboardPro(rlw::Camera camera, rlw::Texture2D texture, rlw::Rectangle source, rlw::Vector3 position, rlw::Vector3 up, rlw::Vector2 size, rlw::Vector2 origin, float rotation, rlw::Color tint);
RAYLIBWRAPPER_API void rlw_UploadMesh(rlw::Mesh *mesh, bool dynamic);
RAYLIBWRAPPER_API void rlw_UpdateMeshBuffer(rlw::Mesh mesh, int index, const void *data, int dataSize, int offset);
RAYLIBWRAPPER_API void rlw_UnloadMesh(rlw::Mesh mesh);
RAYLIBWRAPPER_API void rlw_DrawMesh(rlw::Mesh mesh, rlw::Material material, rlw::Matrix transform);
RAYLIBWRAPPER_API void rlw_DrawMeshInstanced(rlw::Mesh mesh, rlw::Material material, const rlw::Matrix *transforms, int instances);
RAYLIBWRAPPER_API bool rlw_ExportMesh(rlw::Mesh mesh, const char *fileName);
RAYLIBWRAPPER_API rlw::BoundingBox rlw_GetMeshBoundingBox(rlw::Mesh mesh);
RAYLIBWRAPPER_API void rlw_GenMeshTangents(rlw::Mesh *mesh);
RAYLIBWRAPPER_API rlw::Mesh rlw_GenMeshPoly(int sides, float radius);
RAYLIBWRAPPER_API rlw::Mesh rlw_GenMeshPlane(float width, float length, int resX, int resZ);
RAYLIBWRAPPER_API rlw::Mesh rlw_GenMeshCube(float width, float height, float length);
RAYLIBWRAPPER_API rlw::Mesh rlw_GenMeshSphere(float radius, int rings, int slices);
RAYLIBWRAPPER_API rlw::Mesh rlw_GenMeshHemiSphere(float radius, int rings, int slices);
RAYLIBWRAPPER_API rlw::Mesh rlw_GenMeshCylinder(float radius, float height, int slices);
RAYLIBWRAPPER_API rlw::Mesh rlw_GenMeshCone(float radius, float height, int slices);
RAYLIBWRAPPER_API rlw::Mesh rlw_GenMeshTorus(float radius, float size, int radSeg, int sides);
RAYLIBWRAPPER_API rlw::Mesh rlw_GenMeshKnot(float radius, float size, int radSeg, int sides);
RAYLIBWRAPPER_API rlw::Mesh rlw_GenMeshHeightmap(rlw::Image heightmap, rlw::Vector3 size);
RAYLIBWRAPPER_API rlw::Mesh rlw_GenMeshCubicmap(rlw::Image cubicmap, rlw::Vector3 cubeSize);
RAYLIBWRAPPER_API rlw::Material rlw_LoadMaterialDefault(void);
RAYLIBWRAPPER_API bool rlw_IsMaterialValid(rlw::Material material);
RAYLIBWRAPPER_API void rlw_UnloadMaterial(rlw::Material material);
RAYLIBWRAPPER_API void rlw_SetMaterialTexture(rlw::Material *material, int mapType, rlw::Texture2D texture);
RAYLIBWRAPPER_API void rlw_SetModelMeshMaterial(rlw::Model *model, int meshId, int materialId);
RAYLIBWRAPPER_API void rlw_UpdateModelAnimation(rlw::Model model, rlw::ModelAnimation anim, int frame);
RAYLIBWRAPPER_API void rlw_UnloadModelAnimation(rlw::ModelAnimation anim);
RAYLIBWRAPPER_API void rlw_UnloadModelAnimations(rlw::ModelAnimation *animations, int animCount);
RAYLIBWRAPPER_API bool rlw_IsModelAnimationValid(rlw::Model model, rlw::ModelAnimation anim);
RAYLIBWRAPPER_API bool rlw_CheckCollisionSpheres(rlw::Vector3 center1, float radius1, rlw::Vector3 center2, float radius2);
RAYLIBWRAPPER_API bool rlw_CheckCollisionBoxes(rlw::BoundingBox box1, rlw::BoundingBox box2);
RAYLIBWRAPPER_API bool rlw_CheckCollisionBoxSphere(rlw::BoundingBox box, rlw::Vector3 center, float radius);
RAYLIBWRAPPER_API rlw::RayCollision rlw_GetRayCollisionSphere(rlw::Ray ray, rlw::Vector3 center, float radius);
RAYLIBWRAPPER_API rlw::RayCollision rlw_GetRayCollisionBox(rlw::Ray ray, rlw::BoundingBox box);
RAYLIBWRAPPER_API rlw::RayCollision rlw_GetRayCollisionMesh(rlw::Ray ray, rlw::Mesh mesh, rlw::Matrix transform);
RAYLIBWRAPPER_API rlw::RayCollision rlw_GetRayCollisionTriangle(rlw::Ray ray, rlw::Vector3 p1, rlw::Vector3 p2, rlw::Vector3 p3);
RAYLIBWRAPPER_API rlw::RayCollision rlw_GetRayCollisionQuad(rlw::Ray ray, rlw::Vector3 p1, rlw::Vector3 p2, rlw::Vector3 p3, rlw::Vector3 p4);
RAYLIBWRAPPER_API void rlw_InitAudioDevice(void);
RAYLIBWRAPPER_API void rlw_CloseAudioDevice(void);
RAYLIBWRAPPER_API bool rlw_IsAudioDeviceReady(void);
RAYLIBWRAPPER_API void rlw_SetMasterVolume(float volume);
RAYLIBWRAPPER_API float rlw_GetMasterVolume(void);
RAYLIBWRAPPER_API rlw::Wave rlw_LoadWave(const char *fileName);
RAYLIBWRAPPER_API rlw::Wave rlw_LoadWaveFromMemory(const char *fileType, const unsigned char *fileData, int dataSize);
RAYLIBWRAPPER_API bool rlw_IsWaveValid(rlw::Wave wave);
RAYLIBWRAPPER_API rlw::Sound rlw_LoadSound(const char *fileName);
RAYLIBWRAPPER_API rlw::Sound rlw_LoadSoundFromWave(rlw::Wave wave);
RAYLIBWRAPPER_API rlw::Sound rlw_LoadSoundAlias(rlw::Sound source);
RAYLIBWRAPPER_API bool rlw_IsSoundValid(rlw::Sound sound);
RAYLIBWRAPPER_API void rlw_UpdateSound(rlw::Sound sound, const void *data, int sampleCount);
RAYLIBWRAPPER_API void rlw_UnloadWave(rlw::Wave wave);
RAYLIBWRAPPER_API void rlw_UnloadSound(rlw::Sound sound);
RAYLIBWRAPPER_API void rlw_UnloadSoundAlias(rlw::Sound alias);
RAYLIBWRAPPER_API bool rlw_ExportWave(rlw::Wave wave, const char *fileName);
RAYLIBWRAPPER_API bool rlw_ExportWaveAsCode(rlw::Wave wave, const char *fileName);
RAYLIBWRAPPER_API void rlw_PlaySound(rlw::Sound sound);
RAYLIBWRAPPER_API void rlw_StopSound(rlw::Sound sound);
RAYLIBWRAPPER_API void rlw_PauseSound(rlw::Sound sound);
RAYLIBWRAPPER_API void rlw_ResumeSound(rlw::Sound sound);
RAYLIBWRAPPER_API bool rlw_IsSoundPlaying(rlw::Sound sound);
RAYLIBWRAPPER_API void rlw_SetSoundVolume(rlw::Sound sound, float volume);
RAYLIBWRAPPER_API void rlw_SetSoundPitch(rlw::Sound sound, float pitch);
RAYLIBWRAPPER_API void rlw_SetSoundPan(rlw::Sound sound, float pan);
RAYLIBWRAPPER_API rlw::Wave rlw_WaveCopy(rlw::Wave wave);
RAYLIBWRAPPER_API void rlw_WaveCrop(rlw::Wave *wave, int initSample, int finalSample);
RAYLIBWRAPPER_API void rlw_WaveFormat(rlw::Wave *wave, int sampleRate, int sampleSize, int channels);
RAYLIBWRAPPER_API void rlw_UnloadWaveSamples(float *samples);
RAYLIBWRAPPER_API rlw::Music rlw_LoadMusicStream(const char *fileName);
RAYLIBWRAPPER_API rlw::Music rlw_LoadMusicStreamFromMemory(const char *fileType, const unsigned char *data, int dataSize);
RAYLIBWRAPPER_API bool rlw_IsMusicValid(rlw::Music music);
RAYLIBWRAPPER_API void rlw_UnloadMusicStream(rlw::Music music);
RAYLIBWRAPPER_API void rlw_PlayMusicStream(rlw::Music music);
RAYLIBWRAPPER_API bool rlw_IsMusicStreamPlaying(rlw::Music music);
RAYLIBWRAPPER_API void rlw_UpdateMusicStream(rlw::Music music);
RAYLIBWRAPPER_API void rlw_StopMusicStream(rlw::Music music);
RAYLIBWRAPPER_API void rlw_PauseMusicStream(rlw::Music music);
RAYLIBWRAPPER_API void rlw_ResumeMusicStream(rlw::Music music);
RAYLIBWRAPPER_API void rlw_SeekMusicStream(rlw::Music music, float position);
RAYLIBWRAPPER_API void rlw_SetMusicVolume(rlw::Music music, float volume);
RAYLIBWRAPPER_API void rlw_SetMusicPitch(rlw::Music music, float pitch);
RAYLIBWRAPPER_API void rlw_SetMusicPan(rlw::Music music, float pan);
RAYLIBWRAPPER_API float rlw_GetMusicTimeLength(rlw::Music music);
RAYLIBWRAPPER_API float rlw_GetMusicTimePlayed(rlw::Music music);
RAYLIBWRAPPER_API rlw::AudioStream rlw_LoadAudioStream(unsigned int sampleRate, unsigned int sampleSize, unsigned int channels);
RAYLIBWRAPPER_API bool rlw_IsAudioStreamValid(rlw::AudioStream stream);
RAYLIBWRAPPER_API void rlw_UnloadAudioStream(rlw::AudioStream stream);
RAYLIBWRAPPER_API void rlw_UpdateAudioStream(rlw::AudioStream stream, const void *data, int frameCount);
RAYLIBWRAPPER_API bool rlw_IsAudioStreamProcessed(rlw::AudioStream stream);
RAYLIBWRAPPER_API void rlw_PlayAudioStream(rlw::AudioStream stream);
RAYLIBWRAPPER_API void rlw_PauseAudioStream(rlw::AudioStream stream);
RAYLIBWRAPPER_API void rlw_ResumeAudioStream(rlw::AudioStream stream);
RAYLIBWRAPPER_API bool rlw_IsAudioStreamPlaying(rlw::AudioStream stream);
RAYLIBWRAPPER_API void rlw_StopAudioStream(rlw::AudioStream stream);
RAYLIBWRAPPER_API void rlw_SetAudioStreamVolume(rlw::AudioStream stream, float volume);
RAYLIBWRAPPER_API void rlw_SetAudioStreamPitch(rlw::AudioStream stream, float pitch);
RAYLIBWRAPPER_API void rlw_SetAudioStreamPan(rlw::AudioStream stream, float pan);
RAYLIBWRAPPER_API void rlw_SetAudioStreamBufferSizeDefault(int size);
RAYLIBWRAPPER_API void rlw_SetAudioStreamCallback(rlw::AudioStream stream, rlw::AudioCallback callback);
RAYLIBWRAPPER_API void rlw_AttachAudioStreamProcessor(rlw::AudioStream stream, rlw::AudioCallback processor);
RAYLIBWRAPPER_API void rlw_DetachAudioStreamProcessor(rlw::AudioStream stream, rlw::AudioCallback processor);
RAYLIBWRAPPER_API void rlw_AttachAudioMixedProcessor(rlw::AudioCallback processor);
RAYLIBWRAPPER_API void rlw_DetachAudioMixedProcessor(rlw::AudioCallback processor);

#ifdef __cplusplus
} // extern "C"
#endif